### PR TITLE
H5 vol 

### PR DESCRIPTION
**Pull request by guj**

### CODE REVIEW

**Comment by chuckatkins** [comment]
Was there a need to write the whole thing in C rather than C++ and just `extern "C"` the api that hdf needs?

**Comment by chuckatkins** [comment]
@guj it looks like when rebased on the current master / release there's a build failure.  If you can resolve that issue then I can work through the rest of the code and cmake re-organization.

**Comment by guj** [comment]
> @guj it looks like when rebased on the current master / release there's a build failure. If you can resolve that issue then I can work through the rest of the code and cmake re-organization.

done.

**Comment by chuckatkins** [comment]
@guj Reorg of build complete.  Please take a look.  The example you had was too brittle to use as an actual test so please add some proper tests in `testing/h5vol`; you can test for it's enabling via the CMake variable `ADIOS2_HAVE_HDF5_VOL`.

**Review by chuckatkins — APPROVED** [review]

**Comment by guj** [comment]
> @guj Reorg of build complete. Please take a look. The example you had was too brittle to use as an actual test so please add some proper tests in `testing/h5vol`; you can test for it's enabling via the CMake variable `ADIOS2_HAVE_HDF5_VOL`.

done!

**Pull request merged**
