### PR TITLE
Backports bp5 bugfix

### PR DESCRIPTION
**Pull request by vicentebolea**

### CODE REVIEW

**Comment by vicentebolea** [comment]
I added the OLCF ascent commit to get status check for BP5 in XL, we can remove it (or not) before merging.

**Review by eisenhauer — APPROVED** [review]
BP5 changes look good.

**Comment by vicentebolea** [comment]
Hopefully XL passing :crossed_fingers:

**Comment by vicentebolea** [comment]
@eisenhauer nice :), do you think it is a good idea to bring the OLCF Ascent changes to the release? There are all aditions of CI files, no CMake or source code touched.

**Pull request merged**
