### PR TITLE
WIP: try limiting mpich tests to 2 processes only

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Review by vicentebolea — APPROVED** [review]
No failure, no test missing. This looks good to me

**Comment by scottwittenburg** [comment]
Huh, I wasn't expecting that to be the end of it :laughing: 

I see the following testing times from the latest run on this PR:

```
gcc-8-ompi:  ~33m
gcc-9-ompi:  ~29m
gcc10-ompi:  ~26m
gcc11-ompi:  ~30m
gcc10-mpich: ~27m
```

**Comment by vicentebolea** [comment]
Scott you might want to also use this change:
```
diff --cc scripts/ci/gh-actions/run.sh
index 512a62eda,512a62eda..3de015255
--- a/scripts/ci/gh-actions/run.sh
+++ b/scripts/ci/gh-actions/run.sh
@@@ -69,7 -69,7 +69,9 @@@ export TMPDIR="${RUNNER_TEMP}/tmp
  mkdir -p "${TMPDIR}"
  
  # OpenMPI specific setup and workarounds
--if [[ "${GH_YML_MATRIX_PARALLEL}" =~ mpi && "${GH_YML_BASE_OS}" != "Windows" ]]
++if [ "${GH_YML_MATRIX_PARALLEL}" = "mpi" ] \
++  && [ "${GH_YML_MATRIX_PARALLEL}" != "mpich" ] \
++  && [ "${GH_YML_BASE_OS}" != "Windows" ]
  then
    # Quiet some warnings from OpenMPI
    export OMPI_MCA_btl_base_warn_component_unused=0
```
You need this since otherwise we force N=4 as per the main CMakeLists.txt

```
if(ADIOS2_HAVE_MPI)
  if(MPIEXEC_MAX_NUMPROCS LESS 4 AND "$ENV{OMPI_MCA_rmaps_base_oversubscribe}")
    message(STATUS "OpenMPI oversubscribe detected: raising MPIEXEC_MAX_NUMPROCS to 4 for testing")
    set(MPIEXEC_MAX_NUMPROCS 4 CACHE STRING "" FORCE)
  endif()

  # Workaround for MPI forcing the link of C++ bindings
  add_definitions(-DOMPI_SKIP_MPICXX -DMPICH_SKIP_MPICXX)
endif()

```

**Comment by vicentebolea** [comment]
It will be interesting to see if this makes a difference now.

**Comment by scottwittenburg** [comment]
Time spent on the tests (gcc10, shared, mpich) was still around 14m, which is the same as [here](https://github.com/ornladios/ADIOS2/pull/3883#issuecomment-1815195005), so I'm guessing it doesn't make much difference now.

**Comment by vicentebolea** [comment]
I see, if there is no much of a difference now lets keep it n=4. We can close this and re-open later if needed

**Comment by scottwittenburg** [comment]
Ok, closing for now then.

**Pull request closed without merging**
