### PR TITLE
Moved profiling.log to profiling.json format

### PR DESCRIPTION
**Pull request by williamfgc**
Added test for generating profiling.json
Fixed inclusion for NLohmannJson json.hpp in Test
Tested resulting profiling.json on R (jsonlite), Python (json)
and C++ (json for modern C++)

### CODE REVIEW

**Comment by chuckatkins** [comment]
Can you verify whether or not this breaks the windows+visual studio build?  I'm not sure if the problem was dataman itself or json.hpp

**Comment by williamfgc** [comment]
I don't have access to a Windows machine, @pnorbert @JasonRuonanWang @chuckatkins do you have access? json.hpp should be supported on Windows: https://github.com/nlohmann/json#supported-compilers

**Comment by JasonRuonanWang** [comment]
@williamfgc It looks good to me. But I never use the .value method of this JSON implementation, so I am not sure if additional exception catching would be needed, in case the function does not return the correct type. 

I don't have a Windows machine either.

**Comment by pnorbert** [comment]
This PR does not break my windows build.

**Pull request merged**
