### PR TITLE
u8 string literals are ill-formed in C++20

### PR DESCRIPTION
**Pull request by NAThompson**
See http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1423r0.html

### CODE REVIEW

**Comment by williamfgc** [comment]
Looks good to me, it was just a proof that adios2 supports utf-8 as much as C++ does.

**Comment by pnorbert** [comment]
So how does now ADIOS2 support non-English users to put utf-8 text in the data? I know these are just tests and we don't know if anyone is using UTF-8 to store data, but the goal should be to make it work with both C++11 and C++20 compilers.

**Comment by NAThompson** [comment]
@pnorbert : There is no problem with putting utf8 in strings; it's just the u8 prefix that causes the problem. See [here](https://github.com/boostorg/multiprecision/blob/6447d5326dcaffd3f8114cc7f8722fae24694a4a/include/boost/multiprecision/pslq.hpp#L87) for an example of using utf8 in C++ strings.

**Comment by williamfgc** [comment]
@NAThompson is there is a portable way between C++11 and C++20 to do this? I always worked on the assumption that C++ will remain backwards compatible, thanks for bringing this up. I think @pnorbert brings a very valid point. FYI, I'm not aware if we test with more recent C++ standards.

**Comment by pnorbert** [comment]
Then instead of removing these tests, can you just fix them?

**Comment by NAThompson** [comment]
> FYI, I'm not aware if we test with more recent C++ standards.

I checked for this; we do not test other C++ standards; moreover we force C++-11 and C99; see [here](https://github.com/ornladios/ADIOS2/blob/f5da12f0a3fde7dcd6cfa3ab1af8289f74b0b8e9/CMakeLists.txt#L73).

**Comment by NAThompson** [comment]
Closing in favor of #2404

**Pull request closed without merging**
