### PR TITLE
#712 enable attributes in all ranks

### PR DESCRIPTION
**Pull request by williamfgc**
Needed by insitu-viz libs

### CODE REVIEW

**Comment by pnorbert** [comment]
Does this fix only store 1 instance of the attribute if multiple writers define it? We don't want to store N copies of values for each attribute if all N writers define the attributes.

**Comment by williamfgc** [comment]
@pnorbert that would imply adding a collective, N-to-N comparisons, and sorting operations  per attribute. It would be easier to: 1) define attributes  in certain ranks at the user level, similar to global values. `if (rank==0) { io.DefineAttribute...}`.  or, 2) add a flag to DefineAttribute so the user can tell us if it's a constant attribute across all ranks (default), or will vary across ranks (special case).

**Comment by pnorbert** [comment]
No, there is no need for that. Attributes cannot have different values
across processes by definition. We only need to store one value for each
attribute. We need to send the attributes from each rank to the master but
instead of merging like variables, we need to filter and add only
attributes to the metadata list that don't already exist.

**Comment by williamfgc** [comment]
OK, I get it now. Let me work on the deserialization part.

**Pull request merged**
