### PR TITLE
Merging release, needed for readthedocs

### PR DESCRIPTION
**Pull request by williamfgc**

### CODE REVIEW

**Comment by chuckatkins** [comment]
Please do not merge this.  There's a procedure to update master that ensures conflicts don't occur later.  Basically each topic gets merged into master, followed by the release branch when it was merged.  That's then repeated until master is up to date.  There have been several prs merged into release since I last synced them yesterday.  I'll update master this afternoon with all of them.

**Comment by williamfgc** [comment]
@chuckatkins OK, sounds good, please let me know when this is merged later today so I can work on the readthedocs piece. Thanks!

**Comment by chuckatkins** [comment]
@williamfgc it looks like your the project maintainer of the readthedocs instance.  You should be able to edit the project there so that latest points to master and stable points to release.

**Comment by williamfgc** [comment]
@chuckatkins wil do. Their preferred way to edit the project is from the `readthedocs.yml`

**Comment by williamfgc** [comment]
@chuckatkins can you login into readthedocs? It can't find your username

**Comment by chuckatkins** [comment]
It's associated with my GitHub id.  Try my kw email if that doesn't work

**Comment by williamfgc** [comment]
Done!

**Comment by chuckatkins** [comment]
`latest` and `stable` now point to `master` and `release` respectively.  You should be able to iterate on the docs now regardless of whether or not the branches are in sync.  I'll still sync them up again soon but that shouldn't have to hold you up anymore.

**Comment by williamfgc** [comment]
sounds good, thanks.

**Comment by williamfgc** [comment]
@chuckatkins seems both version are broken in readthedocs

**Comment by williamfgc** [comment]
seems `latest` is working after wiping it.

**Pull request closed without merging**
