### PR TITLE
took care of the corner case when no data is written from the steps

### PR DESCRIPTION
**Pull request by guj**
the step subgroup names should still show up

### CODE REVIEW

**Comment by eisenhauer** [comment]
If this fixes #2099 for HDF5, would you please change the PR to also remove from staging-common/CMakeLists.txt the lines:
    # The nobody-writes-data-in-a-timestep tests don't work with HDF5
    list (FILTER HDF5_TESTS EXCLUDE REGEX ".*NoData$")

This will enable that test for HDF5.

**Comment by guj** [comment]
Hi Greg, HalfData is not working due to some limitation of HDF5.
I am working around it. 

- Junmin

**Comment by eisenhauer** [comment]
OK, when you're ready...

**Comment by eisenhauer** [comment]
@guj, is this PR superseded by other updates?

**Comment by guj** [comment]
Hi Greg, I don't expect so. Why?

**Comment by eisenhauer** [comment]
> Hi Greg, I don't expect so. Why?
Well, this PR has been pending for quite a while, and later merged PR #2120 seemed to have a similar topic, contains changes which overlap, etc.  So I was curious if the unique changes in this PR were still needed.  Not a problem if you're still working on them, but with the release pending I was just looking at the PRs that hadn't been merged.

**Comment by guj** [comment]
Hi, Greg, let me sort out the conflict. I thought this pull request was merged awhile back and obviously was left out.

**Comment by guj** [comment]
hi @eisenhauer , 
looks like I had another pull request #2120  that superceded this one. 

so I will close this pull request

**Pull request closed without merging**
