### PR TITLE
update docs/README.md for using conda env

### PR DESCRIPTION
**Pull request by caitlinross**
`docs/requirements.txt` no longer used as of #1586.
`docs/requirements.txt` actually removed in #3134.

This PR adds `docs/requirements.txt` back to the repo, so you can build locally without needing conda and updates `docs/README.md` to provide correct instructions for building docs locally with conda or pip.

### CODE REVIEW

**Review by anagainaru — APPROVED** [review]

**Comment by eisenhauer** [comment]
@vicentebolea Want this in 2.9?

**Comment by vicentebolea** [comment]
@eisenhauer yes

**Review by vicentebolea — APPROVED** [review]

**Comment by caitlinross** [comment]
@vicentebolea It won't let me merge because of the contract tests? It says they're expected but still waiting on them 4 days later.

**Comment by vicentebolea** [comment]
I just merged it, without changes in the source files those builds do not start.

**Pull request merged**
