### PR TITLE
Fix multi-config cmake generate issues with msvc

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Comment by chuckatkins** [comment]
@aronhelser and @williamfgc this should fix the cmake generate issue on vs2017

**Comment by aronhelser** [comment]
For some reason, I haven't hit the problem with bpls again. Instead, I'm getting:
`FAILED: source/adios2/CMakeFiles/adios2.dir/__/__/bindings/C/c/adios2_c_variable.cpp.obj
"C:\PROGRA~2\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe"  /nologo /TP -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING -Dadios2_EXPORTS -IC:\akit\adios\src\source -Isource -IC:\akit\adios\src\bindings\C -IC:\akit\adios\src\bindings\CXX11 -Ithirdparty\KWSys\adios2sys -IC:\akit\adios\src\thirdparty\pugixml\pugixml\src /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /Fosource\adios2\CMakeFiles\adios2.dir\__\__\bindings\C\c\adios2_c_variable.cpp.obj /Fdsource\adios2\CMakeFiles\adios2.dir\ /FS -c C:\akit\adios\src\bindings\C\c\adios2_c_variable.cpp
C:\akit\adios\src\source\adios2/ADIOSMPI.h(12): fatal error C1083: Cannot open include file: 'mpi.h': No such file or directory`

I'm using VS2017, cmake 3.13.0, ninja, and msmpi 9.0.1 (I think). I'd expect `C:\Program Files (x86)\Microsoft SDKs\MPI\Include` to be in the include dirs somehow.

**Comment by aronhelser** [comment]
I also tried Intel MPI, 2019.1.144. I had to run a bat file (`<installdir>\mpi\<package number>\intel64\bin\mpivars.bat `) before compiling, but it found mpi.h then. However, it didn't link - it didn't include the mpi library in the link command. 

So I'm confused...

**Comment by chuckatkins** [comment]
Closing in favor of #1010

**Pull request closed without merging**
