### PR TITLE
Separate the derived variable testing in MPI and not MPI functions

### PR DESCRIPTION
**Pull request by anagainaru**
The vector operations (cross and magnitude), curl and magnitude of curl are left as serial tests.

The scalar and trig derived expressions are tested both serial and with MPI. Each test writes using MPI processes (with X ranks) and reads all the data on rank 0 where correctness is checked.

### CODE REVIEW

**Comment by eisenhauer** [comment]
Whoops.  Merge conflicts...

**Comment by anagainaru** [comment]
> Whoops. Merge conflicts...

Pushing too many things at the same time :)

**Review by eisenhauer — APPROVED** [review]

**Comment by eisenhauer** [comment]
MSAN keeps timing out here.  I'll give it one more shot and then merge it anyway....

**Comment by anagainaru** [comment]
Maybe squash merge, I didn't have time to clean the history

**Pull request merged**
