### PR TITLE
Fix bugs for Fortran column major conversion in SSC

### PR DESCRIPTION
**Pull request by JasonRuonanWang**

### CODE REVIEW

**Comment by JasonRuonanWang** [comment]
@chuckatkins @eisenhauer 

I am having this 893 - Install.Make.Fortran (Failed) error after adding some Fortran based common staging tests.

I thought I have done everything properly so I don't have any clue. Could you help look into it and let me know if I did anything stupid? Thanks.

**Comment by JasonRuonanWang** [comment]
This seems to have nothing to do with the common-staging tests. It still exists after I removed the Fortran tests.

**Comment by JasonRuonanWang** [comment]
@chuckatkins Could you help take a look? Thanks.

**Comment by JasonRuonanWang** [comment]
@bradking Wondering if this could possibly have anything to do with #2022. I don't see any recent Fortran-related changes other than #2022.

**Comment by bradking** [comment]
The `Install.Make.Fortran` test passed when #2022 was merged, and has done so in other PRs since then.

**Pull request merged**
