### PR TITLE
Merge release_27

### PR DESCRIPTION
**Pull request by JasonRuonanWang**

### CODE REVIEW

**Comment by chuckatkins** [comment]
We  most definitely do not want to merge master into release.  If there's branches in master that should be in release then you'll need to make a topic branch on release, cherry pick the commits into it, and then merge that into release.  What's happening here though with master into release is what we're explicitly disallowing in the release process though.

**Comment by JasonRuonanWang** [comment]
@chuckatkins This is to merge release into master, not to merge master into release.

**Comment by chuckatkins** [comment]
Perhaps I misunderstood what it was doing.  Regardless though, syncing release into master is done out of band in a separate process.  I can go ahead and get master in sync though, it's just a different process than this.

**Comment by JasonRuonanWang** [comment]
> Perhaps I misunderstood what it was doing. Regardless though, syncing release into master is done out of band in a separate process. I can go ahead and get master in sync though, it's just a different process than this.

Then please go ahead. I didn't really mean to merge this PR. I just figured that this is the best and fastest way to get your attention :)

**Pull request closed without merging**
