### PR TITLE
Address a number of MSVC build issues

### PR DESCRIPTION
**Pull request by chuckatkins**
Supersedes #1009

### CODE REVIEW

**Comment by chuckatkins** [comment]
@aronhelser With this branch I can successfully configure and build with vs2017 + cmake-3.13 + ms-mpi 10.0 using the Visual Studio generator and MPI being the only feature enabled

**Comment by aronhelser** [comment]
Great! Works for me, too. Was it the generator expression fix that let it find "mpi.h"?

**Comment by aronhelser** [comment]
The changes all look pretty straightforward and reasonable to me. +1
The Travis error seems to just be clang-format on source/utils/adios_iotest/processConfig.cpp, if you want to fix that.

**Comment by aronhelser** [comment]
Looks ready to merge....

**Pull request merged**
