### PR TITLE
Revive Debian builds

### PR DESCRIPTION
**Pull request by KyleFromKitware**

### CODE REVIEW

**Comment by eisenhauer** [comment]
Hmm.  Got an SST failure that I can't explain.  (But why wasn't it rerun?)  I'm adding the link to the failure log so I can find it when I come back to this.
https://pipelines.actions.githubusercontent.com/PPfNBJyJKuC3pl50r7eXFHejOF33EcfeEX5gLWQeH80jntaTjs/_apis/pipelines/1/runs/1408/signedlogcontent/4?urlExpires=2020-05-15T18%3A47%3A26.3554164Z&urlSigningMethod=HMACV1&urlSignature=ZHdAFFbWhcMicMbIMkfWd5%2FOtbWZtA6ATh2xgLU4kAk%3D

**Comment by eisenhauer** [comment]
Please rebase on master to avoid LockGeometry problem.

**Comment by chuckatkins** [comment]
Rebased on master

**Comment by KyleFromKitware** [comment]
The tests passed with a rerun - [this test](https://open.cdash.org/testDetails.php?test=883751637&build=6534413) failed with a timeout last time.

**Pull request merged**
