### PR TITLE
Finalize changes in SST RDMA DP

### PR DESCRIPTION
**Pull request by philip-davis**
Rearrange order of fabric finalize operations to avoid cleanup race condition in verbs.

### CODE REVIEW

**Comment by philip-davis** [comment]
Doing a think with Travis to see if I can fix the flake8 error...will revert later because Chuck probably has a better way of dealing with this.

**Comment by chuckatkins** [comment]
Formatting checks have been moved from Travis to GitHub Actions.  Please rebase on master to pickup the changes.

**Comment by chuckatkins** [comment]
Can this be closed now that #2555 is merged?

**Comment by philip-davis** [comment]
Yes, indeed. Closing!

**Pull request closed without merging**
