### PR TITLE
Install a recent breathe from conda-forge

### PR DESCRIPTION
**Pull request by williamfgc**
Get pip explicitly from conda-forge
Trying to address #2243

### CODE REVIEW

**Comment by chuckatkins** [comment]
The failing Debian builds have been disabled. Please rebase.

**Comment by williamfgc** [comment]
@chuckatkins FYI, there is a Travis failure unrelated to this PR: https://travis-ci.com/github/ornladios/ADIOS2/jobs/335577265

**Comment by chuckatkins** [comment]
Rebased on master after travis fix

**Comment by chuckatkins** [comment]
I've just enabled PR testing on readthedocs so I'm re-pushing this to trigger the new build

**Pull request merged**
