### PR TITLE
Fix shared libs default

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Comment by chuckatkins** [comment]
@williamfgc @guj Please check to verify that this fixes your issue.  If it does then I will merge it.

**Comment by williamfgc** [comment]
@chuckatkins in my Ubuntu setup I have Python 2.7 as default (/usr/bin/python), but CMake picks up python3 (also installed) Found PythonInterp: /usr/bin/python3 (found version "3.5.1") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
-- Found PythonModule_mpi4py: /usr/lib/python3/dist-packages/mpi4py  
That makes ctest fail 
It works just fine on my Mac where Python2.6 and Python2.7 (default) coexist. Hope this helps.

**Comment by chuckatkins** [comment]
I believe that's an unrelated issue to the problem PR is addressing.  Are you ok with this being merged to address the shared lib defaults and creating a new issue to work out how python gets found?

**Comment by williamfgc** [comment]
It's somewhere introduced in the current PR. I don't have that issue with the current master branch using -DADIOS2_USE_SHARED_LIBS. Python 2.7 is picked up on Ubuntu and ctest runs fine.

**Comment by chuckatkins** [comment]
Hmm, ok.  How about if you roll back one commit with `git reset --hard HEAD~1`, does that work for you?

**Comment by williamfgc** [comment]
Still the same, finds python3, but ctest fails
-- Found PythonInterp: /usr/bin/python3 (found version "3.5.1") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
-- Found PythonModule_mpi4py: /usr/lib/python3/dist-packages/mpi4py

**Comment by chuckatkins** [comment]
So, I'd expect it find Python 3 if you have it available since I believe it searches for the newest version it can find.  The bigger question is why does the test fail?  Does it work with MPI disabled?

**Comment by williamfgc** [comment]
I don't see adios2.so when python3 is picked up
Current PR:
/build$ dir lib/python3/dist-packages
adios2.cpython-35m-x86_64-linux-gnu.so
Master:
/build$ dir lib/python2.7/dist-packages
adios2.so

**Comment by chuckatkins** [comment]
That's expected with python3 and is normal working behavior.  It explicitly looks for so's with that long suffix.  Do you get any more details regarding the test failure?  i.e. `ctest -VV -R Python`

**Comment by williamfgc** [comment]
build$ ctest -VV -R Python
UpdateCTestConfiguration  from :/home/wfg/tmp/build/DartConfiguration.tcl
Parse Config file:/home/wfg/tmp/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/wfg/tmp/build/DartConfiguration.tcl
Parse Config file:/home/wfg/tmp/build/DartConfiguration.tcl
Test project /home/wfg/tmp/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 22
    Start 22: PythonBPWrite

22: Test command: /usr/bin/python3 "/home/wfg/tmp/ADIOS2/testing/adios2/bindings/python/TestBPWriteTypes_nompi.py"
22: Environment variables: 
22:  PYTHONPATH=/home/wfg/tmp/build/lib/python3/dist-packages:/home/wfg/workspace/build/lib/python2.7/dist-packages:/home/wfg/workspace/ADIOS2/testing/adios2/bindings/python:
22: Test timeout computed to be: 1500
22: Traceback (most recent call last):
22:   File "/home/wfg/tmp/ADIOS2/testing/adios2/bindings/python/TestBPWriteTypes_nompi.py", line 12, in <module>
22:     from adios2NPTypes import SmallTestData
22:   File "/home/wfg/tmp/ADIOS2/testing/adios2/bindings/python/adios2NPTypes.py", line 9, in <module>
22:     import numpy as np
22: ImportError: No module named 'numpy'
1/1 Test #22: PythonBPWrite ....................***Failed    0.15 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.15 sec

The following tests FAILED:
	 22 - PythonBPWrite (Failed)
Errors while running CTest

**Comment by williamfgc** [comment]
OK, I think this is on me.....looks like I am missing numpy for python3. I take full responsibility.

**Comment by chuckatkins** [comment]
No worries.  It is odd that we were finding python2 before though.  I'll add an additional call to make sure we find numpy as well.

**Comment by chuckatkins** [comment]
So, we're good to go on this one?  I'm clear to merge?

**Comment by williamfgc** [comment]
Thanks @chuckatkins. I will merge if you're ok with it.

**Comment by williamfgc** [comment]
or you can push the button....either way.

**Pull request merged**
