### PR TITLE
Add an explicit path for aligned memory.

### PR DESCRIPTION
**Pull request by chuckatkins**
Fix unaligned memory in `CopyToBuffer`

The issue seems to show up sporadically in ubsan.  This should at least address it for this function.

### CODE REVIEW

**Comment by chuckatkins** [comment]
@KyleFromKitware I believe this is also related to you ubsan failure see in #1932

**Comment by williamfgc** [comment]
@chuckatkins I think it is great to have this. My input is to have it separate from the current CopyToBuffer function and specialize for `long double`, or the future non-standars types, as suggested by @KyleFromKitware in #1932

**Comment by KyleFromKitware** [comment]
Yes, it is related.

**Comment by KyleFromKitware** [comment]
I'm not sure why ubsan is flagging it as it exists right now. Right now it's copying raw bytes, which should be fine from an ubsan perspective. Am I missing something?

**Comment by chuckatkins** [comment]
So, digging more into a few of the implementations for `std::copy`, I'm not sure this will actually accomplish anything.  In `libc++`, any combination of inputs convertible to the same raw pointer types (`vector<t>::iterator` is convertible to `T*` for instance), eventually ends up with a `memmove`.  So really the way to address the long double issue would be to specialize the function as in #1932 but to only invoke the specialization if the alignment is correct for the type.  If the pointers aren't aligned then there's no real choice but to memcpy / memmove and just copy the padding along with it.

**Pull request closed without merging**
