### PR TITLE
Quick fix for the issue 4131. Included only for linux.

### PR DESCRIPTION
**Pull request by dmitry-ganyushin**
FileHTTP.cpp is include in build only for linux until further fix.

### CODE REVIEW

**Comment by eisenhauer** [comment]
Generally I think we’d rather move in the direction of making the code portable rather than excluding certain functionality from certain platforms.  That’s a slippery slope with an unpleasant end.

**Comment by dmitry-ganyushin** [comment]
That is only a quick fix to make build for FreeBSD (untested on FreeBSD)

**Comment by eisenhauer** [comment]
Dmitry, I'm going to close this because PR #4138 takes care of this problem by making the file in question compile on FreeBSD.

**Comment by dmitry-ganyushin** [comment]
Auto tests are missing. How to test functionality?

**Comment by eisenhauer** [comment]
> Auto tests are missing. How to test functionality?
On step at a time.  PR #4138 just adds a #include so the build isn't broken on FreeBSD.  I'll do windows too because that's pretty quick and easy.  Adding tests and other mods will probably wait until we have a performant use case.  For now, just trying to keep this code around in the anticipation that we might have such a case in the future.

**Pull request closed without merging**
