### PR TITLE
Use auto-built docker images

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Comment by chuckatkins** [comment]
@eisenhauer https://open.cdash.org/testDetails.php?test=805856481&build=6118583 looks to be a legit failure, not just a "heisenbug" timeout.

**Comment by eisenhauer** [comment]
Hmm.  The "Cannot bind INET socket" is the cause of the failure here.  That means a bind() operation failed, which may mean too many things running on that host.  So, likely environmental in some way.  (Not that it couldn't maybe be handled better...)

**Comment by chuckatkins** [comment]
> Hmm. The "Cannot bind INET socket" is the cause of the failure here. That means a bind() operation failed, which may mean too many things running on that host.

Right.  It shouldn't be causeing a segfault though.

**Comment by eisenhauer** [comment]
We can make it fail in another way, but fail it will, one way or another.  If we can’t bind sockets, we can’t communicate...

Sent from my iPhone

On Sep 19, 2019, at 9:59 AM, Chuck Atkins <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm. The "Cannot bind INET socket" is the cause of the failure here. That means a bind() operation failed, which may mean too many things running on that host.

Right. It shouldn't be causeing a segfault though.

**Comment by eisenhauer** [comment]
There are a whole lot of “this should fail better” things that need to be addressed, but I’ll admit that they’ve been given lower priority than functionality and performance.

Sent from my iPhone

On Sep 19, 2019, at 9:59 AM, Chuck Atkins <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm. The "Cannot bind INET socket" is the cause of the failure here. That means a bind() operation failed, which may mean too many things running on that host.

Right. It shouldn't be causeing a segfault though.

**Comment by eisenhauer** [comment]
I've opened an issue on making SST fail better.  Some of these failures can created relatively easily, but the bind() failure not so much.  So to the extent that we can recreate how you got this, that would be useful.

**Comment by chuckatkins** [comment]
It's near impossible it seems to reliably reproduce these oversubscription->timeout issues.  I think they will essentially disappear as I get all the other tests marked with the "processes" property.

**Pull request merged**
