### PR TITLE
Korteweg de-Vries equation example

### PR DESCRIPTION
**Pull request by NAThompson**
This should help with #2000.

A couple things:

- I should probably add a "step attribute" for the time.
- I will add graphing ability once the Python binding problems are hammered out.

### CODE REVIEW

**Comment by pnorbert** [comment]
Shouldn't we have this rather in [https://github.com/ornladios/ADIOS2-Examples](https://github.com/ornladios/ADIOS2-Examples)?

**Comment by NAThompson** [comment]
@pnorbert : That's fine; either way. But the fact that I had no clue that the ADIOS2-examples repo existed, along with the existence of an `examples` directory here, does not indicate that many other people will find it. It also appears less well-maintained, so I fear it will be susceptible to bitrot.

**Comment by williamfgc** [comment]
@NAThompson I can help you migrating to the ADIOS2-Examples repo (in my spare time). Reality is, ADIOS2-Examples is easy to maintain as long as ADIOS2 doesn't break its API. As for unit tests, they should be under testing, there is nothing run/verified under examples so it got pretty outdated over time.

**Comment by NAThompson** [comment]
@williamfgc : Ok, cool. I'll open a PR in the examples project.

**Pull request closed without merging**
