### PR TITLE
Changes due to MGARD signature change.

### PR DESCRIPTION
**Pull request by qliu21**

### CODE REVIEW

**Comment by qliu21** [comment]
@williamfgc My impression is that chuck is still working on the Azure pipeline? and therefore these two tests failed? If so, please help merge.

**Comment by williamfgc** [comment]
@chuckatkins please take a look, seems the C compilers are failing. Thanks.

**Comment by chuckatkins** [comment]
@williamfgc I believe it was a build caching issue in the automated image regeneration on dockerhub.  I've disabled the caching and triggered the image rebuilds but it'
ll take a few hours.  I'll keep an eye on it and re-run the azure checks here once they're ready.

**Comment by williamfgc** [comment]
@chuckatkins OK, thanks for heads up. @qliu21 you can always keep doing work rebasing from this branch. Thanks.

**Comment by qliu21** [comment]
Thank you, @chuckatkins @williamfgc

**Comment by qliu21** [comment]
@williamfgc FYI. The tests are passed. Please help review the changes

**Pull request merged**
