### PR TITLE
Bug fix for the Kokkos backend used with a Kokkos application

### PR DESCRIPTION
**Pull request by anagainaru**
If we follow the guideline from Kokkos to link against the library I do not get any error. 
With the lines I am removing from our cmake file the Kokkos backend gives an error related to scratch space issues.

I am not sure why we cannot set the CUDA property for the Kokkos code (I am still trying to find out), but removing these lines fixes the bug. I tested and now we can use CUDA/Kokkos applications with any of the GPU backends in ADIOS (CUDA or Kokkos). @vicentebolea we can discuss this separately in a call if you'd like

The only change now is that applications will need to use the nvcc_wrapper if they want to use the Kokkos backend (which is included in PATH if they use the modules on Summit).

Since with this fix we can use the Kokkos backend, I think we need to merge this for the release and once we figure out why we cannot use the properties we can submit a patch.

### CODE REVIEW

**Review by eisenhauer — DISMISSED** [review]

**Comment by anagainaru** [comment]
Run the CUDA example with the ADIOS Kokkos backend

```
$ ./bin/CudaBPWriteRead_cuda
Using engine BP5
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos::Impl::ParallelReduce< Cuda > requested too much L0 scratch memory
Aborted (core dumped)
```

**Comment by vicentebolea** [comment]
> Run the CUDA example with the ADIOS Kokkos backend
> 
> ```
> $ ./bin/CudaBPWriteRead_cuda
> Using engine BP5
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Kokkos::Impl::ParallelReduce< Cuda > requested too much L0 scratch memory
> Aborted (core dumped)
> ```
> 
> **LATER EDIT** Since Greg's PR was not merged, the Cuda examples are `./bin/CudaBP5WriteRead_cuda` and `./bin/CudaBP4WriteRead_cuda` and not what I used above. The error is the same.

I am trying to replicate this, this seems an UB issue in our invokation of kokkos reduce somewhere which is triggered when we build the source file with a concrete compiler.

**Comment by vicentebolea** [comment]
> > Run the CUDA example with the ADIOS Kokkos backend
> > ```
> > $ ./bin/CudaBPWriteRead_cuda
> > Using engine BP5
> > terminate called after throwing an instance of 'std::runtime_error'
> >   what():  Kokkos::Impl::ParallelReduce< Cuda > requested too much L0 scratch memory
> > Aborted (core dumped)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **LATER EDIT** Since Greg's PR was not merged, the Cuda examples are `./bin/CudaBP5WriteRead_cuda` and `./bin/CudaBP4WriteRead_cuda` and not what I used above. The error is the same.
> 
> I am trying to replicate this, this seems an UB issue in our invokation of kokkos reduce somewhere which is triggered when we build the source file with a concrete compiler.

@anagainaru can you share the cmake flags passed to the kokkos build?

**Comment by anagainaru** [comment]
I am using:
```
Kokkos_ROOT=/path/to/kokkos/install
CMAKE_C_COMPILER=gcc
CMAKE_CXX_COMPILER=/path/to/kokkos/bin/nvcc_wrapper
ADIOS2_USE_CUDA=OFF
ADIOS2_USE_Kokkos=ON
```
with
```
module load cuda/11.4 gcc/10.2.0
```

I am free after 2pm if you want to look at this together.

**Comment by vicentebolea** [comment]
> I am using:
> 
> ```
> Kokkos_ROOT=/path/to/kokkos/install
> CMAKE_C_COMPILER=gcc
> CMAKE_CXX_COMPILER=/path/to/kokkos/bin/nvcc_wrapper
> ADIOS2_USE_CUDA=OFF
> ADIOS2_USE_Kokkos=ON
> ```
> 
> with
> 
> ```
> module load cuda/11.4 gcc/10.2.0
> ```
> 
> I am free after 2pm if you want to look at this together.
Could you also share the flags used to build kokkos?

**Comment by anagainaru** [comment]
Sorry I misread what you were asking :)

```
    -D CMAKE_BUILD_TYPE=RelWithDebInfo
    -D CMAKE_CXX_COMPILER=/path/to/kokkos/bin/nvcc_wrapper

    -D Kokkos_ENABLE_SERIAL=ON
    -D Kokkos_ARCH_POWER9=ON

    -D Kokkos_ENABLE_CUDA=ON
    -D Kokkos_ENABLE_CUDA_LAMBDA=ON
    -D Kokkos_ARCH_VOLTA70=ON

    -D CMAKE_CXX_STANDARD=17
    -D CMAKE_CXX_EXTENSIONS=OFF

    -D CMAKE_POSITION_INDEPENDENT_CODE=TRUE
    -D BUILD_SHARED_LIBS=ON
```

**Comment by vicentebolea** [comment]
@anagainaru I could not find the modulefile for summit, I think that ECP does not provides it for summit, only crusher/sunspot/perlmutter

**Comment by vicentebolea** [comment]
@anagainaru I prepared a deployment of kokkos  that you can load here: /gpfs/alpine/csc303/world-shared/deps/load-kokkos_cuda-3.7.00.sh

**Comment by anagainaru** [comment]
@vicentebolea thanks ! I will reproduce your build tonight and see if there is just a matter of documenting good practices. Will update this PR

**Comment by anagainaru** [comment]
I was able to reproduce Vicente's runs. I can confirm the code is working with Kokkos 3.7 but not with the latest release. I created a minimal reproducer of our problem here: https://github.com/anagainaru/ADIOS-Kokkos-bug and will open a ticket with the Kokkos team. 

We have two options for our release: 
- either we force the Kokkos version to 3.7 and we allow other versions in our next patch or 
- we remove the two lines from CMakeLists.txt and force the nvcc_wrapper for the entire library and we remove this requirement in our next patch 

I am ok with either. Once we choose a solution I will update the PR.

**Comment by vicentebolea** [comment]
@anagainaru I vote for supporting kokkos 3.7 for this release (Since we have schedule by tomorrow) and in master figure out how to do this

**Comment by anagainaru** [comment]
> On the other hand I wonder if it builds with kokkos 4.0

I tried with the zip in the Kokkos release and it does not, only 3.7

**Comment by vicentebolea** [comment]
> I tried with the zip in the Kokkos release and it does not, only 3.7

Thats not good for us, still lets fix this in master since we are out of time and Kokkos 3.7 is contemporary to ADIOS 2.9

**Comment by anagainaru** [comment]
I am giving up, I can't make ADIOS2 work with the latest release the way we are linking it. I think we should remove the two lines and use nvcc_wrapper for our release since this will work for any Kokkos version and with the modules on Summit (as soon as they add Kokkos 3.7). 

If you want to spend time on this Vicente you are welcome to try to make this work in a future patch, but there is no point limiting the Kokkos version in current release.

**Comment by vicentebolea** [comment]
> I am giving up, I can't make ADIOS2 work with the latest release the way we are linking it. I think we should remove the two lines and use nvcc_wrapper for our release since this will work for any Kokkos version and with the modules on Summit (as soon as they add Kokkos 3.7).

Is it a build/linking issue?

**Review by vicentebolea — APPROVED** [review]

**Pull request merged**
