### PR TITLE
kokkos: support ROCM >=6

### PR DESCRIPTION
**Pull request by vicentebolea**
Backports https://github.com/ornladios/ADIOS2/pull/4213

### CODE REVIEW

**Comment by vicentebolea** [comment]
@eugeneswalker

**Review by eisenhauer — APPROVED** [review]

**Comment by anagainaru** [comment]
I would like to better understand, did rocm 6 change the API on detecting the allocation type? Could you send me a link to the rocm documentation about this change?

I want to test this on Frontier to make sure we can't use something that is the same across all rocm versions before we consider this complete.

**Comment by vicentebolea** [comment]
Hi @anagainaru welcome back! Good point.

hipPointerAttribute_t API in:

- ROCM 5.3: https://rocm.docs.amd.com/projects/HIP/en/docs-5.3.3/doxygen/html/structhip_pointer_attribute__t.html
- ROCM 6.1: https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/structhip_pointer_attribute__t.html

Yep, it would have been nice from the AMD rocm team to put some  ``[[deprecated]]`` before phasing out the old attribute.

**Comment by anagainaru** [comment]
Yes you are right, I don't think there is any better way of handling this. I was hoping there would be some other solution to test for the allocation of a buffer but I can't seem to find anything.

**Pull request merged**
