### PR TITLE
Update the tutorial with links to external tutorials

### LINKED ISSUE #3966: Could we add a link to the SC tutorials on readthedocs?
Readthedocs has a tutorial created by @spyridon97 that goes over the examples and covers basic functionality.

It would be nice to have links to some of the more advanced tutorials we are giving:
- there is for example the ECP youtube video here: https://www.youtube.com/watch?v=GvuZLSYqmNs&themeRefresh=1  
- and the SC23 tutorial slides here: https://users.nccs.gov/~pnorbert/ADIOS_tutorial_SC23.pdf

I think some people would find it useful (for me the ECP tutorial was very useful when I first joined). Or @vicentebolea maybe the official website (https://adios-io.org/) could use these links.

### PR DESCRIPTION
**Pull request by anagainaru**
Closes #3966

### CODE REVIEW

**Comment by anagainaru** [comment]
@vicentebolea why are the python packages failing (my changes are in the doc)?

**Review by spyridon97 — APPROVED** [review]

**Comment by anagainaru** [comment]
@vicentebolea it seems the two contract CIs are stuck. Do you know what is happening?

**Comment by vicentebolea** [comment]
> @vicentebolea why are the python packages failing (my changes are in the doc)?

They are enabled but only triggered when changes to the source code. You can merge this without any issue

**Comment by anagainaru** [comment]
> They are enabled but only triggered when changes to the source code. You can merge this without any issue

Since they are required I cannot seem to merge this. This is a print screen of what I see.
Screenshot 2024-01-05 at 9 21 49 AM

**Comment by eisenhauer** [comment]
Bypassing branch protections...

**Pull request merged**
