### PR TITLE
Try 32bits in windows

### PR DESCRIPTION
**Pull request by vicentebolea**
cc @eisenhauer

### CODE REVIEW

**Comment by eisenhauer** [comment]
Hmm...   Didn't end up showing the errors that Axel was getting...  Wonder why...

**Comment by vicentebolea** [comment]
@eisenhauer our 32bits got new errors :tada:

**Comment by eisenhauer** [comment]
> @eisenhauer our 32bits got new errors 🎉

Oddly, still not the warnings that Axel reported, but different ones.  But it's a start, I'll poke at these.

**Comment by ax3l** [comment]
In case we have the chance to get this merged, still appreciate the coverage :)

**Comment by eisenhauer** [comment]
The challenge unfortunately is far beyond getting this to compile on 32-bits.  I suspect that the assumption that size_t is corresponds to 64-bits may be deeply embedded and may be quite difficult to sort out.  Merging this before sorting that would be problematic.  Getting ADIOS to the point where it runs cleanly on both 32 and 64 bit systems might be even more so.

**Comment by vicentebolea** [comment]
Closing this since this work would require a much greater amount of engineering (compatibility between bp file produced in different arch for instance)

**Pull request closed without merging**
