### PR TITLE
Work around double-free/corruption error in XL

### PR DESCRIPTION
**Pull request by KyleFromKitware**
Fixes: #2144

### CODE REVIEW

**Comment by chuckatkins** [comment]
This doesn't completely fix the issue, several tests still hit the double-free.  Are there other places this needs to be made?

**Comment by KyleFromKitware** [comment]
>  Are there other places this needs to be made?

I think so. Investigating now.

**Comment by KyleFromKitware** [comment]
After encountering another, harder-to-debug issue (`corrupted double-linked list`), I decided to back up and see if something is going wrong at a more fundamental level. What I found is that the compiler is linking to both `libibmc++.so.1` and `libstdc++.so.6`. This seems very suspicious to me... seems like a ripe opportunity for conflicting memory management code to step on each other's toes. I'm doing some more investigation now.

**Comment by chuckatkins** [comment]
If you want to debug it in a privileged environment you can use the `ornladios/adios2:power8-el7-xl` docker image I've set up.  You just need to first setup the in-kernel emulation via binfmt-misc: `docker run --rm --privileged multiarch/qemu-user-static:register --reset`.  You should then be able to use a docker container with the XL compiler in an environment you have root on.

**Comment by KyleFromKitware** [comment]
Closing in favor of the fix in #2126.

**Pull request closed without merging**
