### PR TITLE
Change install directory of Gray scott files

### PR DESCRIPTION
**Pull request by spyridon97**
Change install directory of Gray scott files

### CODE REVIEW

**Review by anagainaru — COMMENTED** [review]
Good, could we also export the adios2.xml and settings json files in the same folder as executables?

**Comment by spyridon97** [comment]
> Good, could we also export the adios2.xml and settings json files in the same folder as executables?

@pnorbert suggested this change and did not like the bin directory idea. I am open to anything really, your call.

**Comment by anagainaru** [comment]
> @pnorbert suggested this change and did not like the bin directory idea. I am open to anything really, your call.

It's Norbert's call so I am ok with this. I am ok with just adding in the documentation a mention about where they can find the needed files.

**Comment by spyridon97** [comment]
@pnorbert can I get an approval?

**Comment by vicentebolea** [comment]
Note that normally we install examples and its data/conf files in the `share/packagename` this is what the FHS expects packages to do. If we go ahead with this change we will have to patch our adios2 package across our different platforms to use `share/packagename` since in Unix-like systems we cannot create the directory `/usr/adios`.

**Comment by spyridon97** [comment]
> Note that normally we install examples and its data/conf files in the `share/packagename` this is what the FHS expects packages to do. If we go ahead with this change we will have to patch our adios2 package across our different platforms to use `share/packagename` since in Unix-like systems we cannot create the directory `/usr/adios`.

@pnorbert are you fine with that?

**Comment by vicentebolea** [comment]
I am for reverting this, this change does not make sense. The example binaries are installed at `prefix`/bin and the data/conf files are installed at `prefix`/adios2. The `prefix`/adios2. This makes adios2 example impossible to be installed in any unix-like system.

**Pull request merged**
