### PR TITLE
Memory

### PR DESCRIPTION
**Pull request by williamfgc**
Increased Default Maximum Memory to 200Mb --> Changed to Unlimited per time step.
Added config.xml for the heat transfer example for memory management
(among other parameters) at runtime 

To do:
Copy config.xml to /build/bin, right now the heat transfer example won't
run if config.xml is not found

### CODE REVIEW

**Comment by pnorbert** [comment]
So with these changes, you buffer one output step as long as you don't run out of memory. How does time aggregation behave?

**Comment by williamfgc** [comment]
@pnorbert the same way, time aggregation only updates the time_index as we go forward. Or there is something else time aggregation does?

**Comment by chuckatkins** [comment]
See https://github.com/ornladios/ADIOS2/commit/f6477a1a633eb5f5212da1d808268a1504cd596a for how to deal with the location of the xml config

**Comment by chuckatkins** [comment]
Sorry if I'm missing it but I see what the branch is doing but what bug or problem is it trying to fix?

**Pull request merged**
