### PR TITLE
Documentation and fixing the API for derived variables

### PR DESCRIPTION
**Pull request by anagainaru**
Documentation for API, build, supported operations

Example for writing and reading two derived variables, one storing the data and one storing just stats

### CODE REVIEW

**Review by eisenhauer — APPROVED** [review]
Looks good...

**Comment by vicentebolea** [comment]
I am afraid that we cannot backport this, this PR needs others pr backported that were not listed such as #4275 and it also modifies the signatures of methods in public headers that will break the ABI compatibiltity

**Comment by vicentebolea** [comment]
Oh nevermind, this was not targeted to 2.10.2. Sorry :)

**Comment by anagainaru** [comment]
I will mark Norber's PR as 2.11

**Pull request merged**
