### PR TITLE
Fx100

### PR DESCRIPTION
**Pull request by eisenhauer**
Dill upstream and tests in SST to see if forking a comm thread failed.

### CODE REVIEW

**Comment by eisenhauer** [comment]
@keichi Would you please try this on the Fujitsu FX100 system?  It contains the DILL upstream patch that you supplied, and tests for fork failure on the communication thread.  (It turns out that we return a success or failure value for CMfork_comm_thread, which I simply wasn't checking in SST.  This patch fixes that.)

**Comment by keichi** [comment]
@eisenhauer Thanks! I think the commit for testing fork failure is missing though.

**Comment by eisenhauer** [comment]
Whoops, you're right.  I forgot to commit that before pushing the upstream fixes.  Should be there now.

**Comment by keichi** [comment]
@eisenhauer I've tested on FX100. Build succeeds and SST aborts as intended when stack size is not properly set:

```
[t139@a01-m00-09 build]$ mpiexec -np 4 bin/heatTransfer_write_adios2 ../examples/heatTransfer/heat_sst_ffs.xml foo 2 2 10 10 10 10 : -np 3 bin/heatTransfer_read ../examples/heatTransfer/heat_sst_ffs.xml foo.bp bar 1 3
ADIOS2 SST Engine failed to fork a communication thread.
This is a fatal condition, please check resources or system settings.
Dying now.
ADIOS2 SST Engine failed to fork a communication thread.
This is a fatal condition, please check resources or system settings.
Dying now.
ADIOS2 SST Engine failed to fork a communication thread.
This is a fatal condition, please check resources or system settings.
Dying now.
ADIOS2 SST Engine failed to fork a communication thread.
This is a fatal condition, please check resources or system settings.
Dying now.
ADIOS2 SST Engine failed to fork a communication thread.
This is a fatal condition, please check resources or system settings.
Dying now.
ADIOS2 SST Engine failed to fork a communication thread.
This is a fatal condition, please check resources or system settings.
Dying now.
ADIOS2 SST Engine failed to fork a communication thread.
This is a fatal condition, please check resources or system settings.
Dying now.
```

**Comment by eisenhauer** [comment]
Great.  I think this looks good and will merge...

**Pull request merged**
