### PR TITLE
Add option to use external RapidJSON

### PR DESCRIPTION
**Pull request by KyleFromKitware**

### CODE REVIEW

**Comment by williamfgc** [comment]
@KyleFromKitware rapidjson is currently not being used at all. @chuckatkins was going to reach out see PR #2171

**Comment by KyleFromKitware** [comment]
Per @chuckatkins' comment on #2143:

> It's currently not being used but was added as a transition path away from nlohnann_json both due to performance reasons and issues with compilers we need to support for which workarounds were in conflict with upstream development policies.

This leads me to believe that RapidJSON is the way of the future, and should thus be externalized. I will do the same for nlohnann_json since it is still currently being used.

**Comment by williamfgc** [comment]
Correct, for future releases. I was narrowing it down for the upcoming release. This can be easily reinstated when it is actually used in future releases

**Comment by KyleFromKitware** [comment]
Closing in favor of #2184.

**Pull request closed without merging**
