### PR TITLE
Overload NdCopy instead of adding a new argument for the 2.10 release

### PR DESCRIPTION
**Pull request by anagainaru**
I am not sure how to add this only in the release and not master. I don't think we want this in 2.11

Required so that we can include #4359 in the 2.10 release without breaking the ABI.

### CODE REVIEW

**Comment by vicentebolea** [comment]
Best one is for me to go ahead and merge the the git revert in release210 and rebase these changes in the release210 branch.

**Comment by vicentebolea** [comment]
@anagainaru rebased

**Review by vicentebolea — APPROVED** [review]

**Comment by vicentebolea** [comment]
Screenshot from 2024-10-24 15-09-42

**Comment by anagainaru** [comment]
@vicentebolea great, thanks

**Pull request merged**
