### PR TITLE
Fix performputs buffersize

### PR DESCRIPTION
**Pull request by pnorbert**
…datasize correctly in case of multiple calls of PerformPuts(). Addresses #2320

### CODE REVIEW

**Comment by pnorbert** [comment]
@chuckatkins This test writes 3 datasets, each 721MB (and does this twice testing BP3 and BP4). The dataset is a side effect only, so we could remove each immediately after writing, but testing has no access to thirdparty (`<adios2sys/SystemTools.hxx>` specifically). Do you have any suggestion how to add data removal either in CMakeLists.txt or in the code itself? Removing after test would still require 2.1GB of space, removing each right after writing would still require 721MB of space to write during CI.

**Comment by pnorbert** [comment]
@chuckatkins NVM for this test, now it uses NULL transport to avoid writing to disk at all. 
But in general it would be good to know how to remove output files after a test.

**Comment by pnorbert** [comment]
@chuckatkins @bradking Do you guys have an idea why the sanitizers fail to run this new test?
test 234/235, they print /proc/self/status and the VmSize is ridiculously big here. And they timeout, even though they don't do any IO anymore, just buffer 80MB of data  3*3*3 times.
```
234: After Open():                                 buffer size = 16384        VmSize:	107374517864 kB VmRSS:	  317036 kB 
```

**Comment by bradking** [comment]
Cc: @KyleFromKitware

**Comment by chuckatkins** [comment]
> @chuckatkins This test writes 3 datasets, each 721MB (and does this twice testing BP3 and BP4). ... Do you have any suggestion how to add data removal either in CMakeLists.txt or in the code itself? Removing after test would still require 2.1GB of space, removing each right after writing would still require 721MB of space to write during CI.

@pnorbert We should have the capacity on the test VMs for a 2.1gb working set, so long as it's removed after the test.  The way to accomplish that is through test fixtures.  See the docs here for how to use it: https://cmake.org/cmake/help/v3.7/prop_test/FIXTURES_REQUIRED.html

But essentially it's just:
```
# TestFoo generates some output that needs to be cleaned up
add_test(NAME TestFoo ...)

# Make a "test" that cleans up after foo
add_test(NAME TestFooCleanup
  COMMAND ${CMAKE_COMMAND} -E remove_directory /pth/to/TestFooOutput
)

# Mark it as a cleanup test for the "Foo" fixture
set_tests_properties(TestFooCleanup PROPERTIES FIXTURES_CLEANUP Foo)

# Mark the TestFoo as needing any setup or cleanup defined in the "Foo" fixture
set_tests_properties(TestFoo PROPERTIES FIXTURES_REQUIRED Foo)
```

**Pull request merged**
