### PR TITLE
Inline simplifications.

### PR DESCRIPTION
**Pull request by NAThompson**

### CODE REVIEW

**Comment by NAThompson** [comment]
> Add a unit test to ensure that when selecting multiple blocks, that failure occurs gracefully. Or if selecting blocks that aren't available on the current rank.

(The test we have validates the successful case but does not validate the failure mode.)

**Comment by chuckatkins** [comment]
@NAThompson any idea when we can get the remaining test cases so this can get merged?

**Comment by chuckatkins** [comment]
@NAThompson ping?  Just waiting on some additional test cases so we can merge this and make use if it with the inline engine.

**Comment by chuckatkins** [comment]
Rebased on current `release_27`

**Pull request merged**
