### PR TITLE
Backport from master

### PR DESCRIPTION
**Pull request by vicentebolea**
This include the backports from #3860 and also the manual backports:

- #3850
- #3849
- #3848
- #3847
- #3819
- #3812
- #3799
- #3789
- #3774
- #3767
- #3760
- #3758
- #3739
- #3737
- #3715

The following PR were manually backported and some of its changes were dropped due to conflicts or they were changes of things not included in the releases_29.

- #3715
- #3739
- #3760
- #3758
- #3767
- #3789
- #3812

### CODE REVIEW

**Comment by vicentebolea** [comment]
It passes CI and also the ABI compliance checker:
Screenshot from 2023-10-24 12-09-48

Find the report here:

[NAME 0 to 1 compatibility report.pdf](https://github.com/ornladios/ADIOS2/files/13120615/NAME.0.to.1.compatibility.report.pdf)

**Review by eisenhauer — APPROVED** [review]
Looks good to me...

**Comment by vicentebolea** [comment]
https://github.com/spack/spack/pull/40832

**Comment by vicentebolea** [comment]
https://gitlab.kitware.com/paraview/paraview-superbuild/-/merge_requests/1125

**Pull request merged**
