### PR TITLE
evpath: gen_interface.pl support windows

### PR DESCRIPTION
**Pull request by vicentebolea**
This has to be merged upstream. NEed this PR for testing and patch

### CODE REVIEW

**Comment by eisenhauer** [comment]
The unistd.h failure was addressed in a PR.  Might need to rebase.

**Comment by eisenhauer** [comment]
Let me know and I can merge upstream...

**Comment by vicentebolea** [comment]
@eisenhauer thanks! ready for merging upstream. It might be worth to also do some `:retab` and `gg=G` in gen_interface.pl.

ParaView finally builds with 5.10 after this change: https://gitlab.kitware.com/paraview/paraview-superbuild/-/merge_requests/1188

**Comment by eisenhauer** [comment]
> @eisenhauer thanks! ready for merging upstream. It might be worth to also do some `:retab` and `gg=G` in gen_interface.pl.

vim is a typo...  But yeah, it could probably use a pass through perltidy or something...   This code hasn't seen attention in a while.

> ParaView finally builds with 5.10 after this change: https://gitlab.kitware.com/paraview/paraview-superbuild/-/merge_requests/1188

Nice!

**Comment by vicentebolea** [comment]
overseeded by #4181

**Pull request closed without merging**
