### PR TITLE
fixed a few problems of DataMan / ZeroMQ, added simple Read API to ge…

### PR DESCRIPTION
**Pull request by JasonRuonanWang**
fixed a few problems of DataMan / ZeroMQ, added simple Read API to get the hello world example working again.

### CODE REVIEW

**Comment by JasonRuonanWang** [comment]
Accidentally applied clang-format on third party sources. Will do another one.

**Comment by chuckatkins** [comment]
Did you mean to close this?

**Comment by chuckatkins** [comment]
You can keep the same pr and just ammend the commit and force push the branch.

**Comment by JasonRuonanWang** [comment]
@chuckatkins I think this PR is causing too much overhead in the repository because I accidentally applied clang-format to the third-party directory and then tens of thousands of lines of code have been touched which is not necessary at all. I would close this one and stick with #292

**Pull request closed without merging**
