### PR TITLE
Fix the `ADIOS_USE_{}` variable names to use ADIOS2

### PR DESCRIPTION
**Pull request by anagainaru**
Randomly found this bug when testing the query code.

### CODE REVIEW

**Review by vicentebolea — APPROVED** [review]
:facepalm: haha

Good catch!

**Comment by vicentebolea** [comment]
In the same topic, there is also a comment which might confuse future devs.

```
cmake/ADIOSFunctions.cmake:/* CMake Option: ADIOS_USE_${OPT}=OFF */
```

**Comment by vicentebolea** [comment]
And an example

```→ git grep ADIOS_USE
cmake/ADIOSFunctions.cmake:/* CMake Option: ADIOS_USE_${OPT}=OFF */
cmake/DetectOptions.cmake:if(ADIOS_USE_Kokkos AND ADIOS_USE_CUDA)
cmake/DetectOptions.cmake:  message(FATAL_ERROR "ADIOS2_USE_Kokkos is incompatible with ADIOS_USE_CUDA")
examples/hello/README.md:1. datamanReader (to be deprecated, ADIOS_USE_DataMan=ON)
examples/hello/README.md:1. hdf5Writer (-DADIOS_USE_HDF5=ON)  
```

**Comment by anagainaru** [comment]
Done, I added the other places. You'll need to re-approve :)

**Review by vicentebolea — APPROVED** [review]

**Pull request merged**
