### PR TITLE
Initial C bindings

### PR DESCRIPTION
**Pull request by williamfgc**
Makefile compiles creating libadios2_c.so and hello example runs and creates bp file

To do:
CMake and Testing infrastructure (separate branches)
Verify struct adios2_Engine  forward declaration...Done!

### CODE REVIEW

**Comment by williamfgc** [comment]
@JasonRuonanWang please try again.

**Comment by chuckatkins** [comment]
Is there a compelling reason to make the c bindings optional vs always on?

**Comment by chuckatkins** [comment]
Rather than a separate libadios2_c library, the c bindings can be built into libadios2 and just use a single library to contain both the C and C++ interfaces.

**Comment by williamfgc** [comment]
@pnorbert @chuckatkins @JasonRuonanWang  OK, finally I resused @pnorbert and @chuckatkins  cmake infrastructure to figure out library, examples and testing for the C bindings. I updated the ReadMe.md adding the ADIOS2_USE_C to turn OFF and ON the C bindings. Please try it and run ctest. Thanks!

**Comment by williamfgc** [comment]
@chuckatkins I have no preferences, as long as the user has a clear interface separation between C and C++. Many projects are C++ only...no need for the C bindings per-se, unless they decide to use the C API, which is a waste of features if the projects is C++. In fact, C is just a way to other languages, I am not aware of any scientific application using C, it's either C++ or Fortran.  Python is nicely covered directly with PyBind11. Your call, I have no preference. We'll have libadios2_f when we get to the Fortran bindings.

**Comment by williamfgc** [comment]
@chuckatkins @pnorbert @JasonRuonanWang I am going to merge this PR if there is no more comments. If we decide to unify the library, that can be a separate branch/PR. This is an initial C bindings working implementation as the PR says. For now I want to avoid conflict with future branches touching the same files. Thanks!

**Pull request merged**
