### PR TITLE
Remove operations

### PR DESCRIPTION
**Pull request by williamfgc**
Add API function in C++ `Variable<T>::RemoveOperations();` to allow for on and off compression
Add ZFP tests
Related to #2867

### CODE REVIEW

**Comment by pnorbert** [comment]
This sounds like a good idea, however, we need to make sure BP5 will be able to deal with this. @eisenhauer

**Comment by williamfgc** [comment]
@pnorbert thanks, I agree. This sits at a higher layer (`VariableBase`), so if BP5 supports Operations the same as BP3, BP4 it should be seamless. We can integrate once BP5 have tests for compression.

**Review by eisenhauer — APPROVED** [review]
> This sounds like a good idea, however, we need to make sure BP5 will be able to deal with this. @eisenhauer

Since BP5 wants to put things like operator info in metameta info, not encoding it into every timestep's metadata, we'll have add a mechanism for tracking operator changes, be they additions or deletions, but I'll take care of that later.  So I have no problems with allowing operator removal.

**Comment by williamfgc** [comment]
Thanks @pnorbert @eisenhauer . I will find some time to extend this API call to the other language bindings.

**Pull request merged**
