### PR TITLE
ASAN cleanup

### PR DESCRIPTION
**Pull request by eisenhauer**

### CODE REVIEW

**Review by pnorbert — APPROVED** [review]

**Comment by eisenhauer** [comment]
@anagainaru @pnorbert @vicentebolea This isn't a complete fix to the ASAN issues.  It adds two more suppressions that shouldn't be necessary, but they are deep within EVPath and I haven't sorted yet exactly how they are happening.  For the moment I'd like to get the other fixes in and deal with these last two later.

**Review by pnorbert — APPROVED** [review]

**Comment by pnorbert** [comment]
The code added in this commit is indeed in source/adios2/toolkit/format/bp5/BP5Serializer.cpp, so I don't know what happened. I cannot rebase my branch with release_210 because of this patch, but I can rebase with master branch.

**Comment by eisenhauer** [comment]
Hmm.  Hopefully Vicente can answer because I don't have a clue...

**Comment by vicentebolea** [comment]
@pnorbert this changes are in the release2_10 branch (they were backported). Yes the rebase is complicated due to how many thing we have backported to the release210 branch. I recommend to to `git reset --soft origin/release210` this will just apply your changes on the top of release210 in a 2 ways merge (rather then 3).

**Pull request merged**
