### PR TITLE
Add Python SstWriter example

### PR DESCRIPTION
**Pull request by eisenhauer**

### CODE REVIEW

**Comment by eisenhauer** [comment]
This PR adds a python example for SST, and switching the exchanged types to double from float helps match the default (only?) floatingpoint size in Python as per issue #3398.    (There seem to be unrelated CI failures that may be the result of failures elsewhere (can't find host open.cdash.org ?  Will force-push later to retry.)

**Comment by anagainaru** [comment]
Does this mean we cannot use floats in an application that is coupled with a python code? If yes, we need to document this. 

I would also add a python writer to couple it with the cpp reader (I assume the same behavior will occur).

**Comment by williamfgc** [comment]
> Does this mean we cannot use floats in an application that is coupled with a python code? If yes, we need to document this.

The Float32 type needs to be passed explicitly when creating numpy arrays, the default is Float64. Not a Python, but a numpy thing: https://numpy.org/doc/stable/user/basics.types.html

**Comment by williamfgc** [comment]
This is the low-level Python API, the high-level API just returns the appropriate numpy array and type if the variables is found.

**Pull request merged**
