### PR TITLE
FFS upstream

### PR DESCRIPTION
**Pull request by eisenhauer**
This fixes an OSX 14 problem.

### CODE REVIEW

**Review by vicentebolea — APPROVED** [review]
yay!

**Comment by eisenhauer** [comment]
@anagainaru Would you please check this one too to see if it works on OSX 14?

**Comment by anagainaru** [comment]
> @anagainaru Would you please check this one too to see if it works on OSX 14?

I still see the issue with the version of ffs:
```
  The following configuration files were considered but not accepted:

    /ADIOS2/build/thirdparty/ffs/ffs/ffs-config.cmake, version: 3.0.0

```

**Comment by eisenhauer** [comment]
There may be some unpleasantness because I force-pushed the prior version, which might have left some stuff sitting around when you pulled the fresh version.   (I think this because this change doesn't have the version 3.0.0 stuff in it.)  It might be necessary to delete this branch in your current repo and refetch it, and/or blow away the build directory and rebuild.

**Comment by anagainaru** [comment]
@eisenhauer yes you are right, I did that and now it built just fine. So far it looks good, it's at 20% compiling and no complaints. I'll approve this PR when it finishes

**Review by anagainaru — APPROVED** [review]

**Pull request merged**
