### PR TITLE
Added CacheMan to DataMan

### PR DESCRIPTION
**Pull request by JasonRuonanWang**

### CODE REVIEW

**Comment by JasonRuonanWang** [comment]
@chuckatkins Please review.

**Comment by chuckatkins** [comment]
I updated this to current master.  If these changes are acceptable then I will merge them.

**Comment by JasonRuonanWang** [comment]
Is there anything I need to do?

**Comment by chuckatkins** [comment]
I went through and dropped the using std and added std:: everywhere needed.  Just double check that it still looks ok.

**Comment by JasonRuonanWang** [comment]
Yes, it works. Please go ahead. Thanks.

**Pull request merged**
