### PR TITLE
Testing: Make ADIOS1WriteRead test run in parallel

### PR DESCRIPTION
**Pull request by HaochengLIU**
TO achieve this goal, GoogleTest.cmake is extended to allow
exec_wrapper and SmallTestData.h now would generate data based on
step&world_rank&world_size.

### CODE REVIEW

**Comment by HaochengLIU** [comment]
@chuckatkins Would you please kindly review this MR?

**Comment by pnorbert** [comment]
This parallel testing works on my computer.

**Comment by chuckatkins** [comment]
Fixes #147

**Comment by HaochengLIU** [comment]
@chuckatkins 
Fixed!

**Pull request merged**
