### PR TITLE
clang-format: format cu files

### PR DESCRIPTION
**Pull request by vicentebolea**
I tested that this still format C,C++ files by intentionally adding a commit which introduce format mistakes. The checks for that commit is here:

https://github.com/ornladios/ADIOS2/pull/3011/checks?sha=20ad1d499df3b051d0543bce71c7b3c4a717cfbb

### CODE REVIEW

**Comment by vicentebolea** [comment]
ping @chuckatkins

**Comment by anagainaru** [comment]
#3013 is using the previous style for the cuda example file. Just something to consider when we merge the two PRs

**Comment by vicentebolea** [comment]
@anagainaru yes, this should then go first to master, and later after you rebase you can call this script (`ADIOS2/scripts/ci/scripts/run-clang-format.sh`) to format your CUDA files

**Comment by anagainaru** [comment]
@vicentebolea  Or you could remove the updates to the cuda file from this PR, what is really needed is only the style file

**Comment by vicentebolea** [comment]
@anagainaru the problem with that is that then this Pull request CI format test will not pass.

**Comment by vicentebolea** [comment]
you could do a rebase with -Xours to default to my changes here in case of conflict to resolve the conflicts.

**Review by JasonRuonanWang — APPROVED** [review]

**Comment by JasonRuonanWang** [comment]
@vicentebolea @anagainaru 

Are we agreed on which PR to merge first? This one or #3013?

**Pull request merged**
