### PR TITLE
Revert "Merge pull request #3017 from JieyangChen7/fix-gpu-library-conflict-issue"

### PR DESCRIPTION
**Pull request by vicentebolea**
This reverts commit ebc4c8da40a10b5ab845900f6783e5db9b8960ba, reversing
changes made to f6cf3d80013efe90e327503c54aad23577657440.

The MR #3017 introduces runtime errors an a warning:


Also I want to challenge if we really need this, as commented in the #3017:

> On another topic I am late for this discussion but I am against taking this approach since we are rewriting what is already in Thrust (Adding an internal dependency and increasing the code complexity) and also whether this is really a problem that is for us to solve, the same issue can happen with the stdlibrary/glibc but you do not see libraries re-implementing stdlib implementations, at some point we have to draw a line and say if you want to have ADIOS2 with MGARD and CUDA you have to build both of them with the same CUDA SDK version.

> Another thing is when we also internally ship the library in questions.

```
UpdateCTestConfiguration  from :/home/vicente/Projects/ADIOS2/ADIOS2-build/DartConfiguration.tcl
Parse Config file:/home/vicente/Projects/ADIOS2/ADIOS2-build/DartConfiguration.tcl
 Add coverage exclude regular expressions.
 Add coverage exclude: .*/thirdparty/.*
 Add coverage exclude: .*/testing/.*
 Add coverage exclude: .*/examples/.*
UpdateCTestConfiguration  from :/home/vicente/Projects/ADIOS2/ADIOS2-build/DartConfiguration.tcl
Parse Config file:/home/vicente/Projects/ADIOS2/ADIOS2-build/DartConfiguration.tcl
Test project /home/vicente/Projects/ADIOS2/ADIOS2-build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 883
    Start 883: Engine.BP.*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*.BP4.Serial

883: Test command: /home/vicente/Projects/ADIOS2/ADIOS2-build/bin/Test.Engine.BP.WriteReadZfpCuda.Serial "--gtest_filter=*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*" "BP4"
883: Test timeout computed to be: 1500
883: Note: Google Test filter = */BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*
883: [==========] Running 3 tests from 1 test suite.
883: [----------] Global test environment set-up.
883: [----------] 3 tests from ZFPRate/BPWRZFPCUDA
883: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0
883: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
883: Expected equality of these values:
883:   var_r32.Min() - INCREMENT
883:     Which is: -10
883:   *mmR32.first
883:     Which is: 0
883: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16" (153 ms)
883: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1
883: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
883: Expected equality of these values:
883:   var_r32.Min() - INCREMENT
883:     Which is: -10
883:   *mmR32.first
883:     Which is: 0
883: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32" (2 ms)
883: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2
883: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
883: Expected equality of these values:
883:   var_r32.Min() - INCREMENT
883:     Which is: -10
883:   *mmR32.first
883:     Which is: 0
883: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64" (2 ms)
883: [----------] 3 tests from ZFPRate/BPWRZFPCUDA (157 ms total)
883: 
883: [----------] Global test environment tear-down
883: [==========] 3 tests from 1 test suite ran. (157 ms total)
883: [  PASSED  ] 0 tests.
883: [  FAILED  ] 3 tests, listed below:
883: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16"
883: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32"
883: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64"
883: 
883:  3 FAILED TESTS
1/2 Test #883: Engine.BP.*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*.BP4.Serial ...***Failed    0.44 sec
test 884
    Start 884: Engine.BP.*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*.BP4.MPI

884: Test command: /usr/lib64/mpi/gcc/mpich/bin/mpiexec "-n" "6" "/home/vicente/Projects/ADIOS2/ADIOS2-build/bin/Test.Engine.BP.WriteReadZfpCuda.MPI" "--gtest_filter=*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*" "BP4"
884: Test timeout computed to be: 1500
884: Note: Google Test filter = */BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*
884: [==========] Running 3 tests from 1 test suite.
884: [----------] Global test environment set-up.
884: [----------] 3 tests from ZFPRate/BPWRZFPCUDA
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0
884: Note: Google Test filter = */BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*
884: [==========] Running 3 tests from 1 test suite.
884: [----------] Note: Google Test filter = */BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*
884: [==========] Running 3 tests from 1 test suite.
884: [----------] Global test environment set-up.
884: [----------] 3 tests from ZFPRate/BPWRZFPCUDA
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0Global test environment set-up.
884: [----------] 3 tests from ZFPRate/BPWRZFPCUDA
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0
884: 
884: Note: Google Test filter = */BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*
884: [==========] Running 3 tests from 1 test suite.
884: [----------] Global test environment set-up.
884: [----------] 3 tests from ZFPRate/BPWRZFPCUDA
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0
884: Note: Google Test filter = */BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*
884: [==========] Note: Google Test filter = */BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*
884: [==========] Running 3 tests from 1 test suite.
884: [----------] Global test environment set-up.
884: Running 3 tests from 1 test suite.
884: [----------] Global test environment set-up.
884: [----------] 3 tests from ZFPRate/BPWRZFPCUDA[----------] 3 tests from ZFPRate/BPWRZFPCUDA
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0
884: 
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16" (326 ms)
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16" (326 ms)
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16" (327 ms)
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16" (327 ms)
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16" (328 ms)
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16" (327 ms)
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32"[  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32" (12 ms)
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32" (12 ms)
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32" (12 ms)
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32" (12 ms)
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32" (12 ms)
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2
884:  (12 ms)
884: [ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: ../ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
884: Expected equality of these values:
884:   var_r32.Min() - INCREMENT
884:     Which is: -10
884:   *mmR32.first
884:     Which is: 0
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64" (12 ms)
884: [----------] 3 tests from ZFPRate/BPWRZFPCUDA (351 ms total)
884: 
884: [----------] Global test environment tear-down
884: [==========] 3 tests from 1 test suite ran.[  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64" (12 ms)
884: [----------] 3 tests from ZFPRate/BPWRZFPCUDA (350 ms total)
884: 
884: [----------] Global test environment tear-down
884: [==========] 3 tests from 1 test suite ran. (350 ms total)
884: [  PASSED  ] 0 tests.
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64" (12 ms)
884: [----------] 3 tests from ZFPRate/BPWRZFPCUDA (350 ms total)
884: 
884: [----------] Global test environment tear-down
884: [==========] 3 tests from 1 test suite ran. (350 ms total)
884: [  PASSED  ] 0 tests.
884: [  FAILED  ] 3 tests, listed below:
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16"
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32"
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64"
884: 
884:  3 FAILED TESTS
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64" (12 ms)
884: [----------] 3 tests from ZFPRate/BPWRZFPCUDA (351 ms total)
884: 
884: [----------] Global test environment tear-down
884: [==========] 3 tests from 1 test suite ran. (351 ms total)
884: [  PASSED  ] 0 tests.
884: [  FAILED  ] 3 tests, listed below:
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16"
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32"
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64"
884: 
884:  3 FAILED TESTS
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64" (12 ms)
884: [----------] 3 tests from ZFPRate/BPWRZFPCUDA (351 ms total)
884: 
884: [----------] Global test environment tear-down
884: [==========] 3 tests from 1 test suite ran. (351 ms total)
884: [  PASSED  ] 0 tests.
884: [  FAILED  ] 3 tests, listed below:
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0[  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64" (12 ms)
884: [----------] 3 tests from ZFPRate/BPWRZFPCUDA (352 ms total)
884: 
884: [----------] Global test environment tear-down
884: [==========] 3 tests from 1 test suite ran. (352 ms total)
884: [  PASSED  ] 0 tests.
884: [  FAILED  ] 3 tests, listed below:
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16"
884:  (351 ms total)
884: [  PASSED  ] 0 tests.
884: [  FAILED  ] 3 tests, listed below:
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16"
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32"
884: [  FAILED  ] 3 tests, listed below:
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16"
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32"
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "16"
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32"
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64"[  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32"
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64"
884: 
884:  3 FAILED TESTS
884: [  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64"
884: 
884:  3 FAILED TESTS
884: , where GetParam() = "64"
884: 
884:  3 FAILED TESTS
884: 
884: 
884:  3 FAILED TESTS
2/2 Test #884: Engine.BP.*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*.BP4.MPI ......***Failed    0.84 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   1.37 sec

The following tests FAILED:
	883 - Engine.BP.*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*.BP4.Serial (Failed)
	884 - Engine.BP.*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*.BP4.MPI (Failed)
```

The warning

```
[594/1002] Building CUDA object source/adios2/CMakeFiles/adios2_core.dir/helper/adiosCUDA.cu.o                                                                                                                       
/home/vicente/Projects/ADIOS2/ADIOS2/source/adios2/helper/adiosCUDAReduceImpl.h(123): warning #2912-D: constexpr if statements are a C++17 feature                                                                   
          detected during:                                                                                                                                                                                           
            instantiation of "void <unnamed>::reduce<T,blockSize,nIsPow2,Op>(const T *, T *, size_t) [with T=char, blockSize=1024U, nIsPow2=true, Op=<unnamed>::MinOp]" 
(271): here                                                                                                                                                                                                          
            instantiation of "void <unnamed>::reduce_level<T,Op>(size_t, int, int, const T *, T *) [with T=char, Op=<unnamed>::MinOp]" 
(437): here                                                                                               
            instantiation of "T <unnamed>::reduce<T,Op>(size_t, int, int, int, const T *) [with T=char, Op=<unnamed>::MinOp]" 
/home/vicente/Projects/ADIOS2/ADIOS2/source/adios2/helper/adiosCUDA.cu(25): here                          
            instantiation of "void <unnamed>::CUDAMinMaxImpl(const T *, size_t, T &, T &) [with T=char]"  
/home/vicente/Projects/ADIOS2/ADIOS2/source/adios2/helper/adiosCUDA.cu(49): here                          
            instantiation of "void adios2::helper::CUDAMinMax(const T *, std::size_t, T &, T &) [with T=char]" 
/home/vicente/Projects/ADIOS2/ADIOS2/source/adios2/helper/adiosCUDA.cu(55): here                          
                                                                                                          
/home/vicente/Projects/ADIOS2/ADIOS2/source/adios2/helper/adiosCUDAReduceImpl.h(123): warning #2912-D: constexpr if statements are a C++17 feature
```
```

### CODE REVIEW

**Comment by vicentebolea** [comment]
@JieyangChen7 your contribution was great but we need to polish this more I think, it is better to revert this quickly and re-add it later (if needed) than having a troubled master which wait for our fix/discussion.

**Comment by vicentebolea** [comment]
@anagainaru @JasonRuonanWang

**Comment by anagainaru** [comment]
Yes, the Zfp test that writes/reads with CUDA fails on Summit as well

```bash
againaru@batch4.summit build]$ ./bin/Test.Engine.BP.WriteReadZfpCuda.Serial
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from ZFPRate/BPWRZFPCUDA
[ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0
unknown file: Failure
C++ exception with description "ERROR: ADIOS2 BP5 Engine only supports bp format version 5, found 4 version
" thrown in the test body.
[  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16" (295 ms)
[ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1
/ccs/home/againaru/adios/ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
Expected equality of these values:
  var_r32.Min() - INCREMENT
    Which is: -10
  *mmR32.first
    Which is: 0
[  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32" (6 ms)
[ RUN      ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2
/ccs/home/againaru/adios/ADIOS2/testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp:112: Failure
Expected equality of these values:
  var_r32.Min() - INCREMENT
    Which is: -10
  *mmR32.first
    Which is: 0
[  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64" (6 ms)
[----------] 3 tests from ZFPRate/BPWRZFPCUDA (307 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (307 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/0, where GetParam() = "16"
[  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/1, where GetParam() = "32"
[  FAILED  ] ZFPRate/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/2, where GetParam() = "64"

 3 FAILED TESTS
```

As a general discussion I agree with @vicentebolea and @germasch that I prefer not including parts of another library in ADIOS, but I don't understand the issue to have a strong opinion. 
Maybe @JieyangChen7 can describe it?

**Comment by JasonRuonanWang** [comment]
@vicentebolea

We have spent quite a few days on this and @JieyangChen7 found others complaining about this CUDA bug too. So far the ONLY solution, whether you call it a fix or a work around, is to not use Thrust in ADIOS2. And we have verified that this worked. If anyone can come up with a smarter solution, you are more than welcome to propose or open a pull request. If not, then we probably have to go this way, as making ADIOS2+MGARD GPU work in production is one of our top priority goals at the moment. We have many critical activities pending on this. In the meantime, the GPU API MinMax calculation, I don't think it's used in any production workflows so far, so we have plenty of time to fix it if there is an issue.

@anagainaru The ZFP GPU tests have been always failing on my machine, I don't know if it's the same issue as what you saw on Summit though

**Comment by JasonRuonanWang** [comment]
So here are two options:

1. Anyone helps solve the ADIOS2+MGARD GPU problem. I am happy however you solve it, a full solution or a work around, I don't care. 
2. We fix this MinMax thing and keep the Thrust code in ADIOS2.

**Comment by anagainaru** [comment]
@JasonRuonanWang For me the Zfp tests were passing before (granted I only tested with BP5 and looking at the code now it's using BP4). I will look at the tests again tomorrow morning and make sure the problem is the MinMax.

**Comment by JasonRuonanWang** [comment]
> at some point we have to draw a line and say if you want to have ADIOS2 with MGARD and CUDA you have to build both of them with the same CUDA SDK version.

It's nothing about CUDA SDK version. We have always been using the same CUDA SDK version for everything involved in here. It's a bug that any two apps / libs using Thrust and being linked together will have unpredictable behavior. The bug has been reproduced by others too. I am more than happy if you can help Nvidia fix this bug, but the best Jieyang and I can do here, is to ensure only one library use Thrust.

**Comment by anagainaru** [comment]
I went over the example and the test example and the current code computes the max correct but not the min. 
I think I found the issue, I am fixing it now and will submit a PR with a patch in a bit.

**Comment by JieyangChen7** [comment]
@anagainaru I have fixed the issue. I can submit a PR soon.

**Comment by anagainaru** [comment]
> @anagainaru I have fixed the issue. I can submit a PR soon.

I was busy all morning so I didn't have time to clean things up and submit the PR, the problem is with initializing the reduction to 0 (if the buffer data is negative the max will be 0, if they are positive the min is 0).

**Comment by vicentebolea** [comment]
@JasonRuonanWang I have been investigating this issue and as you say the issue is that as it is thrust is a header only library (I guess because of templates) they add all of their symbols to the adios/mgard libraries. Perhaps the easiest way to deal with this is to build MGARD as a shared library since as I remember "so libs" does not have the concept of object files so there is no change of duplicated symbol error, the linker simply return the first occurrence of the symbol. Another possibly solution if thrust is fully header only is to include the thrust header files within a namespace (probably anonymous namespace)

I am having difficulties building MGARD but I will try this later on.

@JieyangChen7 I appreciate the quick response and the fix. I agree with @JasonRuonanWang that this is the best that we have until we properly fix this.

**Comment by JieyangChen7** [comment]
@vicentebolea MGARD was built as a shared library. If you want to reproduce the issue, there is the build script to build MGARD+ADIOS2:

```
#!/bin/bash
set -x

home_dir=$(pwd)

mgard_dir=${home_dir}/MGARD-test
git clone -b mgard-x git@github.com:JieyangChen7/MGARD.git ${mgard_dir}
cd ${mgard_dir} && git checkout 2510e0e623ad0bfd8b821d4c36a0f9ab33fe36ef
cd ${mgard_dir} && ./build_mgard_cuda.sh

adios_dir=${home_dir}/ADIOS2-test
adios_src_dir=${adios_dir}/src
adios_build_dir=${adios_dir}/build
adios_install_dir=${adios_dir}/install
git clone -b master git@github.com:ornladios/ADIOS2.git ${adios_src_dir}
cd ${adios_src_dir} && git checkout f6cf3d80013efe90e327503c54aad23577657440
cmake -S ${adios_src_dir} -B ${adios_build_dir} \
      -DMGARD_ROOT=${mgard_dir}/install \
      -DADIOS2_USE_CUDA=ON
cmake --build ${adios_build_dir} -j8
ctest --test-dir ${adios_build_dir} -R MGARD
```

**Comment by vicentebolea** [comment]
@JieyangChen7 Thanks for the detailed description of the problem and the solution.

I was able to reproduce the steps you mention, I could build ADIOS2 with MGARD but I did not get any linking error, however I did found the following runtime errors (in this branch and in current master) when running MGARD unit tests as shown here:

```
test 893
      Start 893: Engine.BP.*/BPWriteReadMGARD.BPWRMGARD2D/*.BP5.Serial

893: Test command: /home/vicente/Projects/ADIOS2/ADIOS2-build/bin/Test.Engine.BP.WriteReadMGARD.Serial "--gtest_filter=*/BPWriteReadMGARD.BPWRMGARD2D/*" "BP5"
893: Test timeout computed to be: 1500
893: Note: Google Test filter = */BPWriteReadMGARD.BPWRMGARD2D/*
893: [==========] Running 4 tests from 1 test suite.
893: [----------] Global test environment set-up.
893: [----------] 4 tests from MGARDAccuracy/BPWriteReadMGARD
893: [ RUN      ] MGARDAccuracy/BPWriteReadMGARD.BPWRMGARD2D/0
893: GPUassert: driver shutting down /home/vicente/Projects/ADIOS2/test/MGARD/include/mgard-x/RuntimeX/DeviceAdapters/DeviceAdapterCuda.h 524
893: [ERR]  invalid device function while executing LwpkReo with CUDA (Async-check)
```

CUDA 11.6 (NVIDIA Quadro P1000 Mobile)

**Comment by JasonRuonanWang** [comment]
@vicentebolea It is a runtime error that we said from the very beginning. See Jieyang's original post

> When ADIOS2 and a third-party library (e.g., MGARD) are linked together and both of them use the Thrust/CUB library, calling Thrust/CUB APIs in the third-party libraries can cause runtime errors or unexpected behaviors.

It's just that only when we link the two libraries together we can reproduce the runtime error. The error itself is not a linking error. 

I believe the error you have seen is exactly the same thing as what we have seen.

**Comment by vicentebolea** [comment]
@JasonRuonanWang I see, I can imagine that this is because the linker is picking the wrong "duplicated" symbol somewhere, this is harder to fix, building CUDA enabled sources files fvisibility=hidden comes to my mind but yeah I can see that what we have so far is a more pragmatic solution.

I think that we can close this.

**Comment by germasch** [comment]
FWIW, I've had some troubles getting things to compile even with the script that @JieyangChen7 posted, but I managed to get stuff to build eventually. I didn't see the problem on Summit, but I did encounter an error on x86_64, but it was random (ie., sometimes the test would succeed, sometimes it failed), and the error looks different, too:
```
GPUassert: operation not supported on global/shared address space /ccs/home/kaig1/dbg/MGARD-test/include/mgard-x/RuntimeX/DeviceAdapters/DeviceAdapterCuda.h 734
```

I guess this may be all futile. One thing that might still worth looking at for someone who can actually reproduce it is to see whether the gpu architectures that the code gets compiled for are the same for MGARD / ADIOS2, that'd be about the only guess I'd have left, if anyone still cares...

**Comment by JasonRuonanWang** [comment]
@germasch You may need to checkout a commit from 3 days ago before I merged the first fix from Jieyang. Any commit after that has already fixed this issue. The CUDA versions and the GPU architectures are some of the basic things that we immediately checked after we encountered this problem. I am 100% sure they were all set correctly. We have gone much further than that before coming to a conclusion that we had to implement our own MinMax kernel.

**Pull request closed without merging**
