### PR TITLE
Deactivate campaign recording by default. Use .adios-campaign/ as dir…

### LINKED ISSUE #4148: `adios-campaign` directory
Hi,

With the update to ADIOS v2.10 we see `adios-campaign/` folders appearing in the current working directory of WarpX simulations. It contains some `.db` files it seems.

What is that and is that intentional?

I compiled for a V100 cluster w/ Intel CPUs using
```console
$ cmake
  -S $HOME/src/adios2  \
  -B ${build_dir}/adios2-v100-build  \
  -DADIOS2_USE_Blosc2=ON   \
  -DADIOS2_USE_Fortran=OFF  \
  -DADIOS2_USE_Python=OFF  \
  -DADIOS2_USE_ZeroMQ=OFF  \
  -DCMAKE_INSTALL_PREFIX=${SW_DIR}/adios2-2.10.0
```

I think if this is needed in some form, we should put it into the ADIOS .bp directory because we might have multiple ADIOS2 writers active at the same time for various simulation diagnostics.

first seen in https://github.com/ECP-WarpX/WarpX/pull/4869

cc @pnorbert @guj @franzpoeschel

### PR DESCRIPTION
**Pull request by pnorbert**
…ectory name. Fixes #4148

### CODE REVIEW

**Comment by eisenhauer** [comment]
Changes look good.  WRT the windows build failures:  Something must have changed in the CI images and now we're failing where we used to pass.  I incorporated fixes for this into an Xrootd PR so I could merge it, but that was probably a mistake not do fix that in a separate PR so it could be more easily pulled into release.   If you can cherry-pick these commits, it will fix it: 8c62c5724cd469c86de50b8c93353c0f1ce16e16 and bdc78df63b8924d1e495a88abed5cf7215da6077.

**Comment by pnorbert** [comment]
I don't find these commits.
`This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`

**Comment by eisenhauer** [comment]
Huh.

https://github.com/ornladios/ADIOS2/pull/4167/commits/bdc78df63b8924d1e495a88abed5cf7215da6077
https://github.com/ornladios/ADIOS2/pull/4167/commits/8c62c5724cd469c86de50b8c93353c0f1ce16e16

**Comment by eisenhauer** [comment]
> Huh.
> 
> [bdc78df](https://github.com/ornladios/ADIOS2/commit/bdc78df63b8924d1e495a88abed5cf7215da6077) [8c62c57](https://github.com/ornladios/ADIOS2/commit/8c62c5724cd469c86de50b8c93353c0f1ce16e16)

Oh, I bet because they got squashed upon merge...

**Comment by eisenhauer** [comment]
> Oh, I bet because they got squashed upon merge...

Not sure how best to handle that then...

**Comment by pnorbert** [comment]
And failing to do a patch either.
```
$ git diff  master --  examples/hello/hdf5SubFile/hdf5SubFile.cpp  > patch
$ git apply patch
error: patch failed: examples/hello/hdf5SubFile/hdf5SubFile.cpp:14
error: examples/hello/hdf5SubFile/hdf5SubFile.cpp: patch does not apply
```

**Review by anagainaru — APPROVED** [review]

**Pull request merged**
