### PR TITLE
Remove FindBlosc2

### PR DESCRIPTION
**Pull request by ax3l**
Going forward, it might be easier if we dump the dependency to 2.10.2+
https://github.com/Blosc/c-blosc2/releases/tag/v2.10.2

Related to #3903

### CODE REVIEW

**Comment by vicentebolea** [comment]
I rebased on the top of master, there was some unrelated CI failures in master for a two weeks.

**Comment by ax3l** [comment]
Thanks @vicentebolea 

> I think that the issues that you found are due to the fact that blosc2 could not be installed due to depedencies missing and using as a backup this FindBlosc file.

I cannot see a c-blosc2 install issue here:
https://github.com/openPMD/openPMD-api/pull/1554

**Comment by pnorbert** [comment]
It doesn't hurt to increase the version requirement for blosc2.

**Review by pnorbert — APPROVED** [review]

**Comment by vicentebolea** [comment]
Note that we might not have an issue with our current FindBlosc2.cmake file. The error that @ax3l have been seeing it seems to be unrelated to this file. 

The error that was reported at #3903 seems to be related to the blosc2config.cmake not to be found. 

We might not want to arbitrarily drop dependency to older c-blosc2 since dependending on its last release might hinder users that do not have access to older c-blocs2 versions.

**Comment by vicentebolea** [comment]
This was already done at #4093. Closing

**Pull request closed without merging**
