### PR TITLE
Treat short reads and writes in FilePOSIX

### LINKED ISSUE #905: Short writes are not treated correctly in FilePOSIX transport
Currently, ADIOS2 aborts when POSIX write() writes fewer bytes than requested. Short writes are explicitly allowed in the POSIX specification and need to be treated correctly (repeat write() until no unwritten data is left).

https://github.com/ornladios/ADIOS2/blob/ebb0c217e51ce415e066c5cab3c9b71b53271bf5/source/adios2/toolkit/transport/file/FilePOSIX.cpp#L81-L101

### PR DESCRIPTION
**Pull request by keichi**
Closes #905

### CODE REVIEW

**Comment by keichi** [comment]
You're right, I will fix it.

**Comment by williamfgc** [comment]
@keichi do stdio and fstream need this as well?

**Comment by keichi** [comment]
@pnorbert Please review.

**Comment by keichi** [comment]
@williamfgc Stdio and fstream works on Titan without any problem. I guess it's handling the short reads/writes internally.

**Comment by williamfgc** [comment]
@keichi interesting, this is great learning. Thanks!

**Pull request merged**
