### PR TITLE
Patch up documentation

### PR DESCRIPTION
**Pull request by NAThompson**
It looks like some `.rst` files got hit with `clang-format` and were mangled, so I patched it up as I read through.

Note that the images hosted on imgur are no longer available from within the ORNL network, so slowly we'll want to move them into the project.

### CODE REVIEW

**Comment by pnorbert** [comment]
@eisenhauer, @pnorbert  -- can we please test if we can build the documentation now with the new instructions in README

**Comment by pnorbert** [comment]
I could build the documentation based on docs/README.md, even though I encountered these errors on my Ubuntu 16.04 virtual machine:
```
adios@adiosVM:~/work/ADIOS2/docs$ python3 -m venv .
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv
```
```
(docs) adios@adiosVM:~/work/ADIOS2/docs$ pip3 install -r requirements.txt
...
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 5.4MB/s 
Collecting webcolors==1.11.1 (from -r requirements.txt (line 31))
  Downloading https://files.pythonhosted.org/packages/12/05/3350559de9714b202e443a9e6312937341bd5f79f4e4f625744295e7dd17/webcolors-1.11.1-py3-none-any.whl
Requirement already satisfied: setuptools in ./lib/python3.6/site-packages (from blockdiag==2.0.1->-r requirements.txt (line 3))
Building wheels for collected packages: funcparserlib
  Running setup.py bdist_wheel for funcparserlib ... error
  Complete output from command /home/adios/work/ADIOS2/docs/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k7ppz8a5/funcparserlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpxqibrii6pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for funcparserlib
  Running setup.py clean for funcparserlib
Failed to build funcparserlib
```
I also had 14 warnings, not 2 as expected after talking to you:
```
reading sources... [100%] setting_up/setting_up                                               
WARNING: autodoc: failed to import module 'adios2'; the following exception was raised:
No module named 'adios2'
WARNING: autodoc: failed to import class 'File' from module 'adios2'; the following exception was raised:
No module named 'adios2'
/home/adios/work/ADIOS2/docs/user_guide/source/ecosystem/visualization/vtk.rst:3: WARNING: duplicate label using vtk and paraview, other instance in /home/adios/work/ADIOS2/docs/user_guide/source/ecosystem/visualization.rst
/home/adios/work/ADIOS2/docs/user_guide/source/ecosystem/visualization/vtk.rst:71: WARNING: duplicate label saving the vtk.xml data model, other instance in /home/adios/work/ADIOS2/docs/user_guide/source/ecosystem/visualization.rst
/home/adios/work/ADIOS2/docs/user_guide/source/ecosystem/visualization/vtk.rst:212: WARNING: duplicate label build vtk and paraview with adios 2 support, other instance in /home/adios/work/ADIOS2/docs/user_guide/source/ecosystem/visualization.rst
/home/adios/work/ADIOS2/docs/user_guide/source/engines/dataspaces.rst:55: WARNING: Unexpected indentation.
source/engines/virtual_engines.rst:44: WARNING: Title level inconsistent:

Virtual Engine Setups
---------------------
source/engines/bp4.rst:3: WARNING: duplicate label bp4, other instance in /home/adios/work/ADIOS2/docs/user_guide/source/engines/bp4.rst
source/engines/dataman.rst:3: WARNING: duplicate label dataman for wide area network data staging, other instance in /home/adios/work/ADIOS2/docs/user_guide/source/engines/dataman.rst
/home/adios/work/ADIOS2/docs/user_guide/source/engines/ssc.rst:3: WARNING: duplicate label ssc strong staging coupler, other instance in /home/adios/work/ADIOS2/docs/user_guide/source/engines/engines.rst
/home/adios/work/ADIOS2/docs/user_guide/source/engines/virtual_engines.rst:3: WARNING: duplicate label supported virtual engine names, other instance in /home/adios/work/ADIOS2/docs/user_guide/source/engines/engines.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/adios/work/ADIOS2/docs/user_guide/source/engines/dataspaces.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] setting_up/setting_up                                                
source/ecosystem/visualization/vtk.rst:5: WARNING: undefined label: bp3 (default) (if the link has no caption the label must precede a section header)
/home/adios/work/ADIOS2/docs/user_guide/source/ecosystem/visualization/vtk.rst:5: WARNING: undefined label: bp3 (default) (if the link has no caption the label must precede a section header)
generating indices...  genindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 14 warnings.
```

**Comment by pnorbert** [comment]
... and the html looks okay

**Comment by eisenhauer** [comment]
Built OK (after I installed doxygen).   I got 39 warnings, but html looks OK in a browser (what of it I browsed).

**Comment by NAThompson** [comment]
@pnorbert , @eisenhauer : Thanks for taking a look.

I didn't get the `vtk` warnings, only the `dataspaces` warnings. As it stands this is a lot of code to review, so if you get a chance merge this in and I'll fix the rest as I read through the rest of the docs.

**Comment by NAThompson** [comment]
@pnorbert : Reproduced your observations on Ubuntu 18.04; fix in separate PR.

**Comment by williamfgc** [comment]
@pnorbert the warnings is 'cause I moved from a pip to a conda environment build (experimental with read the docs) a while ago. It requires the python bindings library (`adios2.so`) to be available in your `PYTHONPATH` to find the adios2 module. @NAThompson  yeah, seems imgur is not supported in certain networks (it was at the time this was build), I can see the images at home.

**Comment by NAThompson** [comment]
@williamfgc : I'd like to add your comments to the README, but I couldn't get `PYTHONPATH` set to the correct value so that the error went away:

```
build$ cmake -DADIOS2_USE_Python=ON ../ -G Ninja
build$ ninja # successful
ADIOS2/docs/user_guide$  echo $PYTHONPATH
/home/4nt/ADIOS2/build/lib:/home/4nt/ADIOS2/docs/lib/python3.6/site-packages/adios2/
ADIOS2/docs/user_guide$  make html
...
reading sources... [100%] api_high/api_high                                                                                                  
WARNING: autodoc: failed to import module 'adios2'; the following exception was raised:
No module named 'adios2'
WARNING: autodoc: failed to import class 'File' from module 'adios2'; the following exception was raised:
No module named 'adios2'
```

**Comment by williamfgc** [comment]
@NAThompson let's verify it's the correct path and that `python2` and `python3` are not mixed and that you have all the correct sphinx and breathe dependencies. You should be able to run something like this without errors: 
```
$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import adios2
```

I see the Python High-Level API is generated locally when the adios2 module in reachable.

**Comment by NAThompson** [comment]
@williamfgc : Thanks for your help here; here's my environment:

```
(docs) ➜  docs git:(doc_cleanup) ✗ python3
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D
(docs) ➜  docs git:(doc_cleanup) ✗ python2
Python 2.7.16 (default, Sep  2 2019, 11:59:44)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
(docs) ➜  docs git:(doc_cleanup) ✗ pip3 freeze
alabaster==0.7.12
Babel==2.8.0
blockdiag==2.0.1
breathe==4.18.1
certifi==2019.11.28
chardet==3.0.4
docutils==0.16
funcparserlib==0.3.6
idna==2.9
imagesize==1.2.0
Jinja2==2.11.1
MarkupSafe==1.1.1
mpi4py==3.0.3
numpy==1.19.0
packaging==20.1
Pillow==7.0.0
Pygments==2.5.2
pyparsing==2.4.6
pytz==2019.3
requests==2.23.0
six==1.14.0
snowballstemmer==2.0.0
Sphinx==3.1.2
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-blockdiag==2.0.0
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
urllib3==1.25.8
webcolors==1.11.1
$ python3 -q
>>> import adios2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'adios2'
```

**Comment by williamfgc** [comment]
@NAThompson make sure the Python bindings are enabled. After installation you should see this location, which should be in your `PYTHONPATH`:
```
$ ls /opt/adios2/2.6.0/lib/python3/dist-packages/adios2/
adios2.cpython-36m-x86_64-linux-gnu.so  bp4dbg  __init__.py
```
Hope it helps, and thanks for keeping the docs up to date.

**Pull request merged**
