### PR TITLE
TestBPChangingShapeWithinStep without and with various compressors

### PR DESCRIPTION
**Pull request by pnorbert**
…on turned on. This is an openPMD use case that needs to be checked.

### CODE REVIEW

**Review by anagainaru — APPROVED** [review]
Good to know we support this. Maybe we can test this for MGARD as well.

**Comment by pnorbert** [comment]
New test now works with blosc, mgard and zfp (CPU-only) if they are available.

**Comment by pnorbert** [comment]
I did not dismiss your review, nor requested new review. Was automatic somehow

**Comment by vicentebolea** [comment]
> I did not dismiss your review, nor requested new review. Was automatic somehow

Yes I am in the codeowner file for the cmake files. I think I have to limit it so I am not asked to review everywhere haha. It was good during the release but not needed anymore

**Review by anagainaru — APPROVED** [review]
Haha yes, whenever you push a new commit, the reviews are voided :) Approving again, looks good to me.

**Comment by pnorbert** [comment]
rebased with master

**Comment by pnorbert** [comment]
@vicentebolea Did you change the Windows CI somehow? After rebasing with master suddenly this code is not compiled on Windows:
```
INSTANTIATE_TEST_SUITE_P(
    Multiblock, BPChangingShapeWithinStep,
    ::testing::Values(std::make_tuple("none", paccuracy, 0.0)
#ifdef ADIOS2_HAVE_BLOSC2
                          ,
                      std::make_tuple("blosc", pblosc, 0.0)
#endif
#ifdef ADIOS2_HAVE_MGARD
                          ,
                      std::make_tuple("mgard", paccuracy, 0.001)
#endif
#ifdef ADIOS2_HAVE_ZFP
#ifndef ADIOS2_HAVE_ZFP_CUDA // only test on CPU
                          ,
                      std::make_tuple("zfp", paccuracy, 0.001)
#endif
#endif
                          ));
```

**Comment by pnorbert** [comment]
Cleaned-up the commit history after fixing the build on windows. Ready for review and merge after passing the tests.

**Review by anagainaru — APPROVED** [review]
Approving it one last time

**Pull request merged**
