### PR TITLE
Updating the testing for the GPU backend

### PR DESCRIPTION
**Pull request by anagainaru**
Adding Kokkos and updating CUDA for the latest changes.

### CODE REVIEW

**Comment by anagainaru** [comment]
I am in favor of removing the CUDA testing. It's more code to take care of and we are only testing that the CUDA function does the same as Kokkos (I am splitting between them down the line so we don't need to check high level functionality).

And anyway no CI is triggering CUDA testing anyway so there is no point in keeping it.

**Comment by vicentebolea** [comment]
Note that we have build coverage in CI for CUDA. This has some value by itself. Also we might be able to get a CUDA runner later on through the Spack CI.

**Comment by anagainaru** [comment]
And I'm all for testing, but right now we are not trigger it anywhere and it's just code that needs to be maintained. The CUDA tests would not pass right now because we changed the way the backend is used since we did the testing but nobody noticed because we are not triggering it. I'll add it back once we decide to trigger the testing. At least the Kokkos one I can run from time to time on Frontier.

> Note that we have build coverage in CI for CUDA. This has some value by itself. Also we might be able to get a CUDA runner later on through the Spack CI.

**Review by vicentebolea — APPROVED** [review]

**Comment by vicentebolea** [comment]
This change added regression at master https://open.cdash.org/builds/9940686

**Comment by vicentebolea** [comment]
We missed this because the frontier CI was unavailable for a few weeks

**Pull request merged**
