### PR TITLE
Update ReadMe.md for 2.1.1

### PR DESCRIPTION
**Pull request by pnorbert**

### CODE REVIEW

**Comment by chuckatkins** [comment]
It looks like you accidentally pushed this branch to the main repo instead of your fork.

**Comment by pnorbert** [comment]
Isn't the release made from the main repo this time? I updated the cmake
output in the readme to reflect the current status

**Comment by chuckatkins** [comment]
Yes, but PRs should still be made from a branch on a fork.  The only difference this time is that you're targeting master instead of targeting a release branch/

**Comment by pnorbert** [comment]
sorry, edited on github, it offered to create a branch and make a PR since
master is protected. so it did not actually do that?

**Comment by chuckatkins** [comment]
It did both, which has confused the CI scripts.  The Travis CI scripts are only designed to run on PRs, not direct branches (they get passed different variables and arguments).  If you want to do it directly on github then you can make the edit on your fork, in a branch, and then create a PR.

**Comment by pnorbert** [comment]
okay, I did not know that. I will make the changes properly.

**Pull request closed without merging**
