### PR TITLE
Use one-sided MPI in SSC engine

### PR DESCRIPTION
**Pull request by JasonRuonanWang**

### CODE REVIEW

**Comment by ax3l** [comment]
I just isolated part of a bug fix you also submitted in #1829.
Maybe we can merge my small PR first and you rebase against it? :)

**Comment by JasonRuonanWang** [comment]
@ax3l Actually this PR changes a lot of the fundamental things in SSC, and it no longer uses DataMan serializer now. I have also adjusted the cmake file accordingly in this PR.

**Comment by williamfgc** [comment]
@JasonRuonanWang can you please rebase some of the commits? Makes it easier for us when we have to rebase our own branches. Thanks.

**Comment by ax3l** [comment]
@JasonRuonanWang ok, then really let us merge #1831 first, so we have something referable to cherry-pick from for package managers.
You can then throw out DataMan of SSC in your PR :)

**Comment by JasonRuonanWang** [comment]
@ax3l Sure. If you need it then let's merge your PR first.

**Comment by williamfgc** [comment]
@JasonRuonanWang ignoring requests?

**Pull request merged**
