### PR TITLE
Static adios2-config

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Comment by chuckatkins** [comment]
@pnorbert @williamfgc @JasonRuonanWang can you please see if this works for you guys?

**Comment by williamfgc** [comment]
@chuckatkins are we doing rpath in C and Fortran?

```./adios2-config --cxx-flags
-isystem /include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -pthread -std=gnu++11 ```

```./adios2-config -x
-isystem /include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -pthread -std=gnu++11 -Wl,-rpath,/lib:/usr/lib/x86_64-linux-gnu/openmpi/lib /lib/libadios2.so.2.3.0 -lpthread -L/usr/lib -pthread /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so -Wl,-rpath-link,/lib```


```./adios2-config -f
-DADIOS2_HAVE_MPI_F -I/include/fortran -Wl,-rpath,/lib /lib/libadios2_f.so ```

**Comment by JasonRuonanWang** [comment]
@chuckatkins Do you have a newer version of FindADIOS2.cmake? I was still using some old version which I forgot where I got from. And I am getting these errors.

-- Found 'adios2-config': /opt/adios2/bin/adios2-config
-- Can NOT execute 'adios2-config' - check file permissions
-- The directory provided by 'adios2-config --prefix' does not exist: Error: Unknown argument: --prefix
adios2-config (--help | [--c-flags] [--c-libs] [--cxx-flags] [--cxx-libs] [-fortran-flags] [--fortran-libs])
  --help           Display help information
  -c               Both compile and link flags for the C bindings
  --c-flags        Preprocessor and compile flags for the C bindings
  --c-libs         Linker flags for the C bindings
  -x               Both compile and link flags for the C++ bindings
  --cxx-flags      Preprocessor and compile flags for the C++ bindings
  --cxx-libs       Linker flags for the C++ bindings
  -f               Both compile and link flags for the F90 bindings
  --fortran-flags  Preprocessor and compile flags for the F90 bindings
  --fortran-libs   Linker flags for the F90 bindings
-- Could NOT find ADIOS2 (missing: ADIOS2_LIBRARIES ADIOS2_INCLUDE_DIRS) 
-- Found FLEX: /usr/bin/flex

**Comment by chuckatkins** [comment]
> Do you have a newer version of FindADIOS2.cmake
CMake builds need to use the package configs directly, i.e. remove `FindADIOS2.cmake` entirely.  If that doesn't work correctly then I need to make sure it does.  `adios2-config` is really just a workaround for non-cmake projects.

**Comment by JasonRuonanWang** [comment]
I tried to remove the FindADIOS2.cmake in the package but it sill does not work. 

I get a lot of "undefined reference" errors. Basically everything ADIOS2 is undefined. 

../libcasa_tables.so.3: undefined reference to `void adios2::Engine::Get<std::complex<double> >(adios2::Variable<std::complex<double> >, std::complex<double>*, adios2::Mode)'
../libcasa_tables.so.3: undefined reference to `adios2::Engine::Close(int)'
../libcasa_tables.so.3: undefined reference to `adios2::Variable<std::complex<float> >::SetSelection(std::pair<std::vector<unsigned long, std::allocator<unsigned long> >, std::vector<unsigned long, std::allocator<unsigned long> > > const&)'
../libcasa_tables.so.3: undefined reference to `adios2::Variable<std::complex<float> > adios2::IO::DefineVariable<std::complex<float> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, bool)'
../libcasa_tables.so.3: undefined reference to `adios2::Variable<float>::operator bool() const'


This is the cmake log and it seems that cmake already found ADIOS2:


-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 7.3.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Using namespace casacore.
-- Performing Test HAS_CXX11
-- Performing Test HAS_CXX11 - Success
-- Performing Test HAS_GXX_FORTRAN_RULES
-- Performing Test HAS_GXX_FORTRAN_RULES - Success
-- Performing Test HAS_GCC_FORTRAN_RULES
-- Performing Test HAS_GCC_FORTRAN_RULES - Success
-- Looking for pread
-- Looking for pread - found
-- Looking for pwrite
-- Looking for pwrite - found
-- Found Readline: /usr/lib/x86_64-linux-gnu/libreadline.so  
-- Could NOT find SOFA (missing: SOFA_LIBRARY) 
-- MPI is enabled as required by ADIOS2
CMake Warning (dev) at /opt/adios2/lib/cmake/adios2/ADIOS2Config.cmake:4 (if):
  if given arguments:

    "NOT" "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:321 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found MPI_C: /opt/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /opt/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_Fortran: /opt/openmpi/lib/libmpi_usempif08.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found ADIOS2: /opt/adios2/lib/cmake/adios2/ADIOS2ConfigCommon.cmake (found version "2.3.0") 
-- Found FLEX: /usr/bin/flex  
-- Found BISON: /usr/bin/bison  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- A library with BLAS API found.
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Found CFITSIO: /usr/lib/x86_64-linux-gnu/libcfitsio.so (found suitable version "3.430", minimum required is "3.030") 
-- Found WCSLIB: /usr/lib/x86_64-linux-gnu/libwcs.so (found suitable version "5.18", minimum required is "4.7") 
-- Found MPI: TRUE (found version "3.1") found components:  C CXX 
-- ENABLE_TABLELOCKING is turned off as required by MPI
-- Found Pthreads: /usr/lib/x86_64-linux-gnu/libpthread.so  
CMake Warning at measures/CMakeLists.txt:8 (message):
  No ephemerides data found in the specified DATA_DIR
  ("/opt/casacore/share/casacore/data"), so the location must be specified at
  runtime.  If you have preinstalled casacore data, specify the location with
  -DDATA_DIR.


-- Looking for python2 specific environment...
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.15", minimum required is "2") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.15rc1", minimum required is "2") 
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   python
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.15") 
-- Found NumPy: version "1.15.4" /home/w4g/.local/lib/python2.7/site-packages/numpy/core/include
-- CMAKE_SYSTEM .......... = Linux-4.15.0-45-generic
-- CMAKE_BUILD_TYPE ...... = Release
-- Modules to be built ... = casa;tables;scimath_f;scimath;measures;meas;fits;ms;msfits;derivedmscal;lattices;mirlib;coordinates;images;python
-- BUILD_SHARED_LIBS ..... = ON
-- ENABLE_RPATH .......... = ON
-- CMAKE_INSTALL_NAME_DIR  = /opt/casacore/lib
-- ENABLE_TABLELOCKING ... = OFF
-- USE_THREADS ........... = ON
-- USE_OPENMP ............ = OFF
-- USE_MPI ............... = ON
-- USE_STACKTRACE ........ = OFF
-- CMAKE_CXX_COMPILER .... = /usr/bin/c++
-- CMAKE_CXX_FLAGS ....... = -fcx-fortran-rules -Wextra -Wall -W -Wpointer-arith -Woverloaded-virtual -Wwrite-strings -pedantic -Wno-long-long -fsigned-char -DNDEBUG -std=c++11 -pthread
-- DATA directory ........ = /opt/casacore/share/casacore/data
-- DL library? ........... = /usr/lib/x86_64-linux-gnu/libdl.so
-- Pthreads library? ..... = /usr/lib/x86_64-linux-gnu/libpthread.so
-- Readline library? ..... = /usr/lib/x86_64-linux-gnu/libreadline.so;/usr/lib/x86_64-linux-gnu/libncurses.so
-- BLAS library? ......... = /usr/lib/x86_64-linux-gnu/libopenblas.so
-- LAPACK library? ....... = /usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so
-- WCS library? .......... = /usr/lib/x86_64-linux-gnu/libwcs.so;/usr/lib/x86_64-linux-gnu/libm.so
-- SOFA library? ......... = SOFA_LIBRARY-NOTFOUND
-- CFitsio library? ...... = /usr/lib/x86_64-linux-gnu/libcfitsio.so;/usr/lib/x86_64-linux-gnu/libm.so
-- ADIOS2 library? ....... = 
-- HDF5 library? ......... = 
-- FFTW3 library? ........ = 
-- BUILD_PYTHON .......... = ON
-- BUILD_PYTHON3 ......... = OFF
-- PYTHON2_EXECUTABLE ......... = /usr/bin/python2
-- PYTHON2_LIBRARIES........... = /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- PYTHON2_NUMPY_INCLUDE_DIRS . = /home/w4g/.local/lib/python2.7/site-packages/numpy/core/include
-- PYTHON2_Boost_LIBRARIES .... = /usr/lib/x86_64-linux-gnu/libboost_python.so
-- PYTHON2_Boost_INCLUDE_DIRS . = /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/w4g/casacore/build

**Comment by JasonRuonanWang** [comment]
The software I am trying to compile is 

https://github.com/casacore/casacore.git

**Comment by chuckatkins** [comment]
@JasonRuonanWang it with this now.  I added the variables in the pckage config for backwards compatibility

**Comment by chuckatkins** [comment]
> @chuckatkins are we doing rpath in C and Fortran?

We're not explicitly doing it, the flags are being automatically added by cmake.

> ./adios2-config --cxx-flags 
> ```
> -isystem /include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -pthread -std=gnu++11 
> ```

Something else seems broken here (the install prefix is missing from the paths).  What are you're build and install dirs and what os / platform are you on so I can try to reproduce it?

**Comment by JasonRuonanWang** [comment]
@chuckatkins I am still getting the same errors. It looks to me that the ADIOS2 cmake file is found 

-- Found ADIOS2: /opt/adios2/lib/cmake/adios2/ADIOS2ConfigCommon.cmake (found version "2.3.0") 

But the library is not actually found.

-- CFitsio library? ...... = /usr/lib/x86_64-linux-gnu/libcfitsio.so;/usr/lib/x86_64-linux-gnu/libm.so
-- ADIOS2 library? ....... = 
-- HDF5 library? ......... =

**Comment by chuckatkins** [comment]
There was a typo in the package config that I just fixed.  Try it now.

**Comment by chuckatkins** [comment]
> Something else seems broken here (the install prefix is missing from the paths). What are you're build and install dirs and what os / platform are you on so I can try to reproduce it?

@williamfgc nevermind, it was an issue with path resolution of self.  You should get the full paths now.

**Comment by JasonRuonanWang** [comment]
@chuckatkins Still the same thing. Could you try the following:

git clone https://github.com/casacore/casacore.git
cd casacore
rm cmake/FindADIOS2.cmake
mkdir build
cd build
cmake .. -DUSE_ADIOS=ON 

and see?

**Comment by chuckatkins** [comment]
@JasonRuonanWang I installed into `/home/khq.kitware.com/chuck.atkins/Code/adios2/install/work`, set `ADIOS2_DIR` to the install prefix, and then ran

> cmake .. -DUSE_ADIOS2=ON

I get:
```
...
-- Found ADIOS2: /home/khq.kitware.com/chuck.atkins/Code/adios2/install/work/lib64/cmake/adios2/adios2-config.cmake (found version "2.3.0") 
...
-- ADIOS2 library? ....... = adios2::adios2
...
```
and then everything builds and links correctly.

I also made the following change just to clean it up a bit, but it's not necessary:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1aa6d4fe7..3f849c95a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -245,11 +245,6 @@ if (NOT (HAVE_PREAD AND HAVE_PWRITE))
         message(FATAL_ERROR "Casacore requires pread and pwrite functionality" )
 endif (NOT (HAVE_PREAD AND HAVE_PWRITE))
 
-# FindADIOS2 uses environment variables, so set it if needed.
-if (ADIOS2_ROOT_DIR)
-    set (ENV{ADIOS2_ROOT} ${ADIOS2_ROOT_DIR})
-endif (ADIOS2_ROOT_DIR)
-
 # FindHDF5 uses environment variables, so set it if needed.
 if (HDF5_ROOT_DIR)
     set (ENV{HDF5_ROOT} ${HDF5_ROOT_DIR})
@@ -318,7 +313,7 @@ find_package (SOFA)
 if (USE_ADIOS2)
     set(USE_MPI ON)
     message (STATUS "MPI is enabled as required by ADIOS2")
-    find_package (ADIOS2)
+    find_package (ADIOS2 REQUIRED CONFIG)
 endif (USE_ADIOS2)
 if (USE_HDF5)
     find_package (HDF5 REQUIRED)
@@ -364,14 +359,10 @@ if (Boost_FOUND)
     include_directories (${Boost_INCLUDE_DIRS})
     add_definitions(-DHAVE_BOOST)
 endif (Boost_FOUND)
-if (USE_ADIOS2)
 if (ADIOS2_FOUND)
     include_directories (${ADIOS2_INCLUDE_DIRS})
     add_definitions(-DHAVE_ADIOS2)
-else (ADIOS2_FOUND)
-    message(FATAL_ERROR "Casacore is configured to use ADIOS2 but ADIOS2_ROOT_DIR is not defined.")
 endif (ADIOS2_FOUND)
-endif (USE_ADIOS2)
 if (HDF5_FOUND)
     include_directories (${HDF5_INCLUDE_DIRS})
     add_definitions(-DHAVE_HDF5)
```

**Comment by JasonRuonanWang** [comment]
@chuckatkins How did you set ADIOS2_DIR? I tried to export **ADIOS2_DIR=/opt/adios2** as an environmental variable. I also tried **cmake .. -DADIOS2_DIR**, and the I also tried **ADIOS2=/opt/adios2 cmake ..**  

But none of these was picked up by cmake...

**Comment by chuckatkins** [comment]
@JasonRuonanWang let's take this offline in slack

**Pull request merged**
