### PR TITLE
Allow plugin operators to take advantage of the estimated size API

### PR DESCRIPTION
**Pull request by rupertnash**
Hi Team ADIOS!

I greatly appreciate the new `GetEstimatedSize` API for operators - thanks @pnorbert (as I see you committed that in 931941e).

I would like this to work for plugin operators also, so please consider these changes which implement this :) 

I am of course happy to accept revisions.

### CODE REVIEW

**Comment by eisenhauer** [comment]
Two things would help us get to the next step.  First, rebase your changes on current master.  Second, ADIOS uses clang-format version 16.  If you could reformat your files with that, it would get us past the first CI failure.  (If you're on a machine with docker installed, there is a ADIOS script that will use a docker image with the correct version of clang-format to do this for you.  That tends to be easier.   Look at ADIOS2/scripts/ci/scripts/run-clang-format.sh )

**Comment by rupertnash** [comment]
No problem. No docker on ARCHER2 and I can't face trying to convert to Singularity. We have clang format 15, so I've tried that. I'll fix manually if not quite what's required.

**Comment by eisenhauer** [comment]
@pnorbert, these look good to me, but as you added this functionality I'd ask you to look it over before merging.

**Review by anagainaru — COMMENTED** [review]
I would add a test for this because it's hard to tell if you considered everything when computing the size. Looks good at a first glance.

**Comment by rupertnash** [comment]
When you say testing, are you proposing I extend the example plugin operator (the encrypt with libsodium one)? If so, I'm happy to do that.

I did search for tests of the `PluginOperator` class in the testing/adios2 directory but didn't spot any.

**Comment by anagainaru** [comment]
> When you say testing, are you proposing I extend the example plugin operator (the encrypt with libsodium one)? If so, I'm happy to do that.
> 
> I did search for tests of the `PluginOperator` class in the testing/adios2 directory but didn't spot any.
:) that is fair, we do not have testing for this.  We will deal with testing on our side. @pnorbert will review this PR.

**Comment by pnorbert** [comment]
The sodium based encryption operator is tested by 
`ctest -VV -R Install.CMake.EncryptionOperator`
which builds and runs `examples/plugins/operator/examplePluginOperator*.cpp`.

For this to pass, one has to build WITHOUT examples (`-DADIOS2_BUILD_EXAMPLES=OFF`), otherwise the preliminary `ctest -R Install.Setup` will fail. 

So if you modify the encrytion operator source, it will be tested.

**Comment by rupertnash** [comment]
When I tried the ctest command it didn't find anything:
```
ctest -VV -R Install.CMake.EncryptionOperator
UpdateCTestConfiguration  from :/home/e609/e609/rwn-e609/adios2-build/sizes/DartConfiguration.tcl
 Add coverage exclude regular expressions.
 Add coverage exclude: .*/thirdparty/.*
 Add coverage exclude: .*/testing/.*
 Add coverage exclude: .*/examples/.*
UpdateCTestConfiguration  from :/home/e609/e609/rwn-e609/adios2-build/sizes/DartConfiguration.tcl
Test project /home/e609/e609/rwn-e609/adios2-build/sizes
Constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
No tests were found!!!
```

Let's see what CI thinks... Have a great weekend and hope we can get this merged next week :)

**Comment by pnorbert** [comment]
Do you build with testing on? Check the report at the end of the cmake run.
```
2024-03-01T18:26:12.3055408Z   Features:
2024-03-01T18:26:12.3055870Z     Library Type: shared
2024-03-01T18:26:12.3056439Z     Build Type:   Debug
2024-03-01T18:26:12.3056966Z     Testing: ON
2024-03-01T18:26:12.3057445Z     Examples: ON
```

The CI has tested the encryption operator, this PR is good to go.

**Review by pnorbert — APPROVED** [review]

**Pull request merged**
