### PR TITLE
Continuous integration on circle (parallel)

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Comment by chuckatkins** [comment]
@scottwittenburg please take a look

**Comment by scottwittenburg** [comment]
Looks like it's working as you described.

:+1:

**Comment by chuckatkins** [comment]
It's still missing proper branch names.  Could you pull this into your branch and fix the branch names?  Then I think it should be good to go.

**Comment by scottwittenburg** [comment]
CircleCI does not seem to give us the real branch names when building from a fork:

https://discuss.circleci.com/t/access-real-branch-name-for-pull-request-fork-build/907

**Pull request merged**
