### PR TITLE
Testing for BP5 using GPU buffers for read and write

### PR DESCRIPTION
**Pull request by anagainaru**
Using continuous buffers, testing the sync and deferred modes.

### CODE REVIEW

**Comment by JieyangChen7** [comment]
@anagainaru I will take a look and let you know.

**Comment by JieyangChen7** [comment]
@anagainaru The min/max seems to work fine on my side. I run the test 20 times and I could not reproduce the issue. But I do get the following error. It seems that the data you read out from ADIOS does not match the data you wrote when using the CUDA memory space.

```
jieyang@jieyang-Thelio:~/dev/ADIOS2/build$ ./bin/Test.Engine.BP.WriteReadCuda.Serial
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from Rate/BPWRCUDA
[ RUN      ] Rate/BPWRCUDA.ADIOS2BPWRCUDA/0
/home/jieyang/dev/ADIOS2/testing/adios2/engine/bp/TestBPWriteReadCuda.cpp:148: Failure
Expected: (std::abs(r32o[i] - r32s[i])) < (EPSILON), actual: 99 vs 1.19209e-07
t=0 i=0 rank=0 r32o=99.000000 r32s=0.000000
[  FAILED  ] Rate/BPWRCUDA.ADIOS2BPWRCUDA/0, where GetParam() = "deferred" (532 ms)
[ RUN      ] Rate/BPWRCUDA.ADIOS2BPWRCUDA/1
/home/jieyang/dev/ADIOS2/testing/adios2/engine/bp/TestBPWriteReadCuda.cpp:148: Failure
Expected: (std::abs(r32o[i] - r32s[i])) < (EPSILON), actual: 99 vs 1.19209e-07
t=0 i=0 rank=0 r32o=99.000000 r32s=0.000000
[  FAILED  ] Rate/BPWRCUDA.ADIOS2BPWRCUDA/1, where GetParam() = "sync" (1 ms)
[----------] 2 tests from Rate/BPWRCUDA (533 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (533 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] Rate/BPWRCUDA.ADIOS2BPWRCUDA/0, where GetParam() = "deferred"
[  FAILED  ] Rate/BPWRCUDA.ADIOS2BPWRCUDA/1, where GetParam() = "sync"

 2 FAILED TESTS
```
I try to print out the CUDA and host data. Here is the output:

```
r32o[0]:99   r32s[0]:0
r32o[1]:-10   r32s[1]:1
r32o[2]:-10   r32s[2]:2
r32o[3]:-10   r32s[3]:3
r32o[4]:-10   r32s[4]:4
r32o[5]:-10   r32s[5]:5
r32o[6]:-10   r32s[6]:6
r32o[7]:-10   r32s[7]:7
r32o[8]:-10   r32s[8]:8
r32o[9]:-10   r32s[9]:9
r32o[10]:-10   r32s[10]:10
r32o[11]:-10   r32s[11]:11
r32o[12]:-10   r32s[12]:12
r32o[13]:-10   r32s[13]:13
r32o[14]:-10   r32s[14]:14
r32o[15]:-10   r32s[15]:15
r32o[16]:-10   r32s[16]:16
r32o[17]:-10   r32s[17]:17
r32o[18]:-10   r32s[18]:18
r32o[19]:-10   r32s[19]:19
r32o[20]:-10   r32s[20]:20
r32o[21]:-10   r32s[21]:21
r32o[22]:-10   r32s[22]:22
r32o[23]:-10   r32s[23]:23
r32o[24]:-10   r32s[24]:24
r32o[25]:-10   r32s[25]:25
r32o[26]:-10   r32s[26]:26
r32o[27]:-10   r32s[27]:27
r32o[28]:-10   r32s[28]:28
r32o[29]:-10   r32s[29]:29
r32o[30]:-10   r32s[30]:30
r32o[31]:-10   r32s[31]:31
r32o[32]:-10   r32s[32]:32
r32o[33]:-10   r32s[33]:33
r32o[34]:-10   r32s[34]:34
r32o[35]:-10   r32s[35]:35
r32o[36]:-10   r32s[36]:36
r32o[37]:-10   r32s[37]:37
r32o[38]:-10   r32s[38]:38
r32o[39]:-10   r32s[39]:39
r32o[40]:-10   r32s[40]:40
r32o[41]:-10   r32s[41]:41
r32o[42]:-10   r32s[42]:42
r32o[43]:-10   r32s[43]:43
r32o[44]:-10   r32s[44]:44
r32o[45]:-10   r32s[45]:45
r32o[46]:-10   r32s[46]:46
r32o[47]:-10   r32s[47]:47
r32o[48]:-10   r32s[48]:48
r32o[49]:-10   r32s[49]:49
r32o[50]:-10   r32s[50]:50
r32o[51]:-10   r32s[51]:51
r32o[52]:-10   r32s[52]:52
r32o[53]:-10   r32s[53]:53
r32o[54]:-10   r32s[54]:54
r32o[55]:-10   r32s[55]:55
r32o[56]:-10   r32s[56]:56
r32o[57]:-10   r32s[57]:57
r32o[58]:-10   r32s[58]:58
r32o[59]:-10   r32s[59]:59
r32o[60]:-10   r32s[60]:60
r32o[61]:-10   r32s[61]:61
r32o[62]:-10   r32s[62]:62
r32o[63]:-10   r32s[63]:63
r32o[64]:-10   r32s[64]:64
r32o[65]:-10   r32s[65]:65
r32o[66]:-10   r32s[66]:66
r32o[67]:-10   r32s[67]:67
r32o[68]:-10   r32s[68]:68
r32o[69]:-10   r32s[69]:69
r32o[70]:-10   r32s[70]:70
r32o[71]:-10   r32s[71]:71
r32o[72]:-10   r32s[72]:72
r32o[73]:-10   r32s[73]:73
r32o[74]:-10   r32s[74]:74
r32o[75]:-10   r32s[75]:75
r32o[76]:-10   r32s[76]:76
r32o[77]:-10   r32s[77]:77
r32o[78]:-10   r32s[78]:78
r32o[79]:-10   r32s[79]:79
r32o[80]:-10   r32s[80]:80
r32o[81]:-10   r32s[81]:81
r32o[82]:-10   r32s[82]:82
r32o[83]:-10   r32s[83]:83
r32o[84]:-10   r32s[84]:84
r32o[85]:-10   r32s[85]:85
r32o[86]:-10   r32s[86]:86
r32o[87]:-10   r32s[87]:87
r32o[88]:-10   r32s[88]:88
r32o[89]:-10   r32s[89]:89
r32o[90]:-10   r32s[90]:90
r32o[91]:-10   r32s[91]:91
r32o[92]:-10   r32s[92]:92
r32o[93]:-10   r32s[93]:93
r32o[94]:-10   r32s[94]:94
r32o[95]:-10   r32s[95]:95
r32o[96]:-10   r32s[96]:96
r32o[97]:-10   r32s[97]:97
r32o[98]:-10   r32s[98]:98
r32o[99]:-10   r32s[99]:99

```

**Comment by anagainaru** [comment]
Thank you @JieyangChen7 

That is so strange, I'll take a look today

**Comment by anagainaru** [comment]
With the new fix (#3041) all CUDA tests pass on system76 and summit

**Pull request merged**
