### PR TITLE
Fix Windows Testing build

### PR DESCRIPTION
**Pull request by eisenhauer**

### CODE REVIEW

**Comment by eisenhauer** [comment]
This was broken when Python is present for the build, which is apparently not the case for our Windows CI.

**Comment by vicentebolea** [comment]
@eisenhauer that makes sense, however, I cannot see Python enabled in any of our Windows builds.

**Comment by eisenhauer** [comment]
> @eisenhauer that makes sense, however, I cannot see Python enabled in any of our Windows builds.

It's not, but that's just the explanation for why we didn't know this was broken...

**Comment by vicentebolea** [comment]
> It's not, but that's just the explanation for why we didn't know this was broken...

I see, how about enabling python to see if this fixes it(or at least move us to an step closer to have python in Win)?

**Comment by eisenhauer** [comment]
So, I can say that it fixes it in my Windows Visual Studio build (which has python present).  We can also change a CI to do this.  (But if we're adding CIs, I'd probably prioritize Issue #4025 .  We definitely have someone that needs that.)

**Review by vicentebolea — APPROVED** [review]

**Pull request merged**
