### PR TITLE
Merge pull request #3823 from eisenhauer/SstMemSel

### PR DESCRIPTION
**Pull request by vicentebolea**
Add Memory Selection to SST, and prototype a mechanism for running st…

(cherry picked from commit c503940b06020fcbc1731424cca42f7f76dd4512)

### CODE REVIEW

**Review by eisenhauer — APPROVED** [review]

**Comment by vicentebolea** [comment]
Passing ABI checker:
Screenshot from 2023-10-24 18-05-38

Merging after crusher build

**Comment by vicentebolea** [comment]
Crusher lustre storage is stuck or something, lets wait until it comes back.

**Comment by caitlinross** [comment]
@vicentebolea when will this be merged? We need this for the SC tutorial. We're building from the release_29 branch for that.

**Comment by vicentebolea** [comment]
@vicentebolea when will this be merged? We need this for the SC tutorial. We're building from the release_29 branch for that.

I was waiting for the crusher CI to return to normality, I am hoping that tomorrow evening or Wednesday it will be resolve since they normally perform maintenance on Tuesdays.

I am not too strong about it, if you need this today|tomorrow lets go ahead and merge

**Comment by caitlinross** [comment]
Yeah we need it now. We're trying to finalize the VM for the tutorial. FYI @pnorbert we'll have to rebuild things. I didn't realize this wasn't already merged.

**Pull request merged**
