### PR TITLE
added exceptions in insitumpi

### PR DESCRIPTION
**Pull request by JasonRuonanWang**
The insitumpi engine will return successfully when there is only writer (or reader) launched. This is a little confusing when the MPI environment is getting complicated, for example, running cheetah workflow on Summit. In this case it's very hard for users to directly tell whether the writers and readers are launched using correct split MPI communicators. So even if they are not launched correctly, both the writers and readers are still going to finish successfully, but of course in this case data is not going to be correct at all. So it's better to throw an exception when there is no writers or no readers launched.

### CODE REVIEW

**Comment by chuckatkins** [comment]
Is it feasible to add a simple test case for this to ensure the exception gets thrown?

**Comment by JasonRuonanWang** [comment]
@chuckatkins Should be feasible. Let me work on that.

**Comment by JasonRuonanWang** [comment]
@pnorbert Some staging-common tests assume InsituMPI can be executed with only writers or only readers. So if I add exceptions in this case, then those staging-common tests will fail. It may need some work to modify the staging-common testing list. Do you still want to go ahead? If not I can drop this PR.

**Comment by pnorbert** [comment]
I added those tests to make sure they work fine as expected. Now the
expected behavior is that they throw and exception. Can you modify the
tests accordingly? Thanks

**Comment by JasonRuonanWang** [comment]
@chuckatkins This has been stuck since last night. How can I restart it? I don't see a link which I can click or anything.

**Pull request merged**
