### PR TITLE
Cleaned python files.

### PR DESCRIPTION
**Pull request by dmitry-ganyushin**
Cleaned python files with pylint.

### CODE REVIEW

**Comment by chuckatkins** [comment]
Is there value in adding pylint to the travis formatting checks in addition to flake8?

**Comment by chuckatkins** [comment]
Also, see #2234 for the unrelated SST test failures and re-base once it's been addressed

**Comment by NAThompson** [comment]
@dmitry-ganyushin : I just read through these diffs and they look good. All should go green with a rebase.

**Comment by chuckatkins** [comment]
The transition to python 3 has been merged.  Please rebase this on master and add an additional pylint check to the travis formatting check with this.  That will allow us to maintain changes like this one.

Thanks for this cleanup.

**Comment by dmitry-ganyushin** [comment]
flake8 syntax checking is analogous to pylint syntax checking and should capture major problems. Closing this PR in favor of #2424

**Pull request closed without merging**
