### PR TITLE
replaced uint with size_t 

### PR DESCRIPTION
**Pull request by guj**
as reported in: 
https://github.com/ornladios/ADIOS2/issues/3638

### CODE REVIEW

**Comment by eisenhauer** [comment]
@guj I'd see this as a bug, so maybe target to release_29 rather than master(so that it goes into the 2.9.1 release) and tag it as backport to master (and @vicentebolea will manage that bit) ?

**Comment by guj** [comment]
> @guj I'd see this as a bug, so maybe target to release_29 rather than master(so that it goes into the 2.9.1 release) and tag it as backport to master (and @vicentebolea will manage that bit) ?

Fine with me.  Double checking with @vicentebolea.  Shall I merge to release_29 instead of master?

**Comment by vicentebolea** [comment]
master, this MR changes the signature of public headers functions.

**Comment by guj** [comment]
> master, this PR changes the signature of public headers functions.

OK Thanks!

**Comment by vicentebolea** [comment]
Do we need this for the next patch release?

**Comment by guj** [comment]
> Do we need this for the next patch release?

Guess not urgently.

**Comment by eisenhauer** [comment]
Actually, I think I need to push back on the public headers argument.  I don't see that this is in any way a "public" header.  It doesn't get installed, so it's not going to be referenced outside the ADIOS build.  The two functions affected are not consumed outside of the h5vol build.  Is there a conceivable way that putting this into a release would do more than let ADIOS compile in an environment in which it is currently broken?

**Comment by vicentebolea** [comment]
> . I don't see that this is in any way a "public" header.

@eisenhauer you are right, my bad, I thought that this header gets installed but it is not the case. I am not too familiar about the H5Vol component, but I can see now that it is intended to be used as a plugin.

@guj This is change is in an internal function that does not affect the ABI of the plugin thus it should be good to go :). Please merge to master and I will backported with other MRs to release_29.

**Comment by guj** [comment]
@eisenhauer  @vicentebolea 
Please approve so I can merge :)

**Review by vicentebolea — APPROVED** [review]

**Comment by ax3l** [comment]
> master, this PR changes the signature of public headers functions.

Just FYI, I will patch this into any Windows-related package manager I found for 2.9.0 - so you can also add it to master @vicentebolea :)

**Pull request merged**
