### PR TITLE
add support for libpressio as an operator

### PR DESCRIPTION
**Pull request by JasonRuonanWang**
This PR is to replace #2676 which got automatically closed due to having the same branch name as master. Please refer to #2676 for original information @robertu94 provided.

### CODE REVIEW

**Comment by robertu94** [comment]
@JasonRuonanWang weird, I've never seen that cause a problem before.  It look's like you've done what you've asked me to do.  Do you need me to do anything else?

**Comment by JasonRuonanWang** [comment]
> @JasonRuonanWang weird, I've never seen that cause a problem before. It look's like you've done what you've asked me to do. Do you need me to do anything else?

I think it's fine now. But if you want to make updates please use this branch instead of master :)

**Comment by robertu94** [comment]
@JasonRuonanWang I can't see the output of the msan run, but since the LibPressio code isn't built by default, I'm guessing that the test failure wasn't caused by this PR

**Comment by JasonRuonanWang** [comment]
It's caused by a cmake warning. I will look into it later

```
CMake Warning at cmake/DetectOptions.cmake:112 (find_package):
  By not providing "FindLibPressio.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "LibPressio", but CMake did not find one.

  Could not find a package configuration file provided by "LibPressio" with
  any of the following names:

    LibPressioConfig.cmake
    libpressio-config.cmake

  Add the installation prefix of "LibPressio" to CMAKE_PREFIX_PATH or set
  "LibPressio_DIR" to a directory containing one of the above files.  If
  "LibPressio" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:144 (include)


CMake Warning at cmake/DetectOptions.cmake:113 (find_package):
  By not providing "Findstd_compat.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "std_compat", but CMake did not find one.

  Could not find a package configuration file provided by "std_compat" with
  any of the following names:

    std_compatConfig.cmake
    std_compat-config.cmake

  Add the installation prefix of "std_compat" to CMAKE_PREFIX_PATH or set
  "std_compat_DIR" to a directory containing one of the above files.  If
  "std_compat" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:144 (include)
```

**Comment by robertu94** [comment]
That warning is caused by not being able to find the cmake find_package dependencies for  LibPressio and it's only required dependency std_compat.

I'm surprised this didn't cause a warning/error in the other configurations since it did here.

How would you prefer to install LibPressio for unit/integration testing?

**Comment by JasonRuonanWang** [comment]
We probably need to write a FindLibPressio.cmake file and a Findstd_compat.cmake, and put them in ADIOS2/cmake to tell cmake how to find the header and library files of LibPressio. If you look at cdash, many tests had these two warnings. 

I am fine with any method to install it. Once it works I will add it to DataMan engine and write some tests.

**Comment by robertu94** [comment]
These files get generated by LibPressio Cmake files. We just need to install the in a place that cmake looks for them. 


https://cmake.org/cmake/help/latest/command/find_package.html

**Comment by JasonRuonanWang** [comment]
I guess the warning is for cases where there is no LibPressio installed. I am sure if you actually have it installed in somewhere and export that directory to CMAKE_MODULE_PATH then this warning will go away. But it should allow tests to run warning-free if there is actually does not find LibPressio. If you look at the directory ADIOS2/cmake, there are many FindBlahblah.cmake which I guess deals with this situation. I am not a cmake expert, this is only my guess :)

**Comment by germasch** [comment]
The solution may just be to do
```
if(ADIOS2_USE_LIBPRESSIO STREQUAL AUTO) 
 find_package(LibPressio QUIET CONFIG)
 find_package(std_compat QUIET CONFIG)
elseif(ADIOS2_USE_LIBPRESSIO)
  find_package(LibPressio REQUIRED CONFIG)
  find_package(std_compat REQUIRED CONFIG)
endif()
```

Since it sounds like those packages do install their own cmake configs, no find module is required, and by telling cmake so (`CONFIG`), those warnings should go away.

I do think there's another problem, though: If only LibPressio is found, but not std_compat, it'll still try to enable it.

**Comment by JasonRuonanWang** [comment]
@germasch Thanks for the point. I will just try this change and see how it works.

**Comment by JasonRuonanWang** [comment]
@robertu94 It seems to pass all the tests now. Another question, what is the std_compat library? I was trying to find a reference in LibPressio but it does not have a link or something that I can refer to. I saw this repository https://github.com/thierry-martinez/stdcompat but I am not sure if it is the library that LibPressio requires...

**Comment by robertu94** [comment]
@JasonRuonanWang std_compat contains a bunch of backports for c++14,17, and 20 library features that LibPressio uses to support older compilers. It's a separate package because some other applications/libraries that my collaborators use it independently of LibPressio

https://github.com/robertu94/std_compat

**Comment by JasonRuonanWang** [comment]
@robertu94 Sounds great. But I couldn't get it compiled on my Mac systems. I have opened an issue in your repository. Can you help have a look? Thanks.

**Pull request merged**
