### PR TITLE
Fix bad cmake include

### LINKED ISSUE #1742: Current master is broken when configuring with zfp
when using `-DADIOS2_USE_ZFP=ON` the following error shows up:

```
-- Verifying Fortran/CXX Compiler Compatibility - Success
CMake Error at testing/examples/heatTransfer/TestBPFileMx1_zfp.cmake:6 (include):
  include could not find load file:

    ADIOS2Functions
Call Stack (most recent call first):
  testing/examples/heatTransfer/CMakeLists.txt:13 (include)


CMake Error at cmake/ADIOSFunctions.cmake:165 (set_property):
  set_property given TEST names that do not exist:

    HeatTransfer.BP3.zfp.Mx1.Validate

Call Stack (most recent call first):
  testing/examples/heatTransfer/TestBPFileMx1_zfp.cmake:33 (SetupTestPipeline)
  testing/examples/heatTransfer/CMakeLists.txt:13 (include)


CMake Error at cmake/ADIOSFunctions.cmake:168 (set_property):
  set_property given TEST names that do not exist:

    HeatTransfer.BP3.zfp.Mx1.Validate

Call Stack (most recent call first):
  testing/examples/heatTransfer/TestBPFileMx1_zfp.cmake:33 (SetupTestPipeline)
  testing/examples/heatTransfer/CMakeLists.txt:13 (include)


CMake Error at cmake/ADIOSFunctions.cmake:171 (set_property):
  set_property given TEST names that do not exist:

    HeatTransfer.BP3.zfp.Mx1.Validate

Call Stack (most recent call first):
  testing/examples/heatTransfer/TestBPFileMx1_zfp.cmake:33 (SetupTestPipeline)
  testing/examples/heatTransfer/CMakeLists.txt:13 (include)


CMake Error at cmake/ADIOSFunctions.cmake:165 (set_property):
  set_property given TEST names that do not exist:

    HeatTransfer.BP4.zfp.Mx1.Validate

Call Stack (most recent call first):
  testing/examples/heatTransfer/TestBPFileMx1_zfp.cmake:61 (SetupTestPipeline)
  testing/examples/heatTransfer/CMakeLists.txt:13 (include)


CMake Error at cmake/ADIOSFunctions.cmake:168 (set_property):
  set_property given TEST names that do not exist:

    HeatTransfer.BP4.zfp.Mx1.Validate

Call Stack (most recent call first):
  testing/examples/heatTransfer/TestBPFileMx1_zfp.cmake:61 (SetupTestPipeline)
  testing/examples/heatTransfer/CMakeLists.txt:13 (include)


CMake Error at cmake/ADIOSFunctions.cmake:171 (set_property):
  set_property given TEST names that do not exist:

   HeatTransfer.BP4.zfp.Mx1.Validate

Call Stack (most recent call first):
  testing/examples/heatTransfer/TestBPFileMx1_zfp.cmake:61 (SetupTestPipeline)
  testing/examples/heatTransfer/CMakeLists.txt:13 (include)


-- Found MPI: TRUE (found version "3.1") found components:  C 

ADIOS2 build configuration:
  ADIOS Version: 2.4.0.442
  C++ Compiler : GNU 7.4.0 
    /usr/bin/c++

  Fortran Compiler : GNU 7.4.0 
    /usr/bin/f95

  Installation prefix: /home/wgodoy/tmp/adios2
        bin: bin
        lib: lib
    include: include
      cmake: lib/cmake/adios2
     python: lib/python3.6/site-packages

  Features:
    Library Type: shared
    Build Type:   Debug
    Testing: ON
    Build Options:
      Blosc    : ON
      BZip2    : ON
      ZFP      : ON
      SZ       : ON
      MGARD    : ON
      PNG      : ON
      MPI      : ON
      DataMan  : OFF
      Table    : OFF
      SSC      : OFF
      SST      : ON
      DataSpaces: OFF
      ZeroMQ   : ON
      HDF5     : ON
      Python   : ON
      Fortran  : ON
      SysVShMem: ON
      Profiling: ON
      Endian_Reverse: OFF
    RDMA Transport for Staging: Unconfigured

-- Configuring incomplete, errors occurred!
See also "/home/wgodoy/tmp/ADIOS2-build/CMakeFiles/CMakeOutput.log".
See also "/home/wgodoy/tmp/ADIOS2-build/CMakeFiles/CMakeError.log".
```

### PR DESCRIPTION
**Pull request by chuckatkins**
Fixes #1742

### CODE REVIEW

**Comment by pnorbert** [comment]
Thanks for fixing this. I could not figure it out however trivial it seems. In general, I have a question about the cmake process. 

The wrong include does not cause any problem on my VM (Ubuntu 16.04, cmake 3.12.0) when configuring from scratch. I assume because this test is in a subdirectory of the bp tests, the parent's include of the correct functions work fine. So here: why does this wrong include not fail all the time?

But then if I change any test, make will trigger cmake to re-run and this error shows up. What is the difference in the configuration process that it fails with this error?

**Comment by chuckatkins** [comment]
> I assume because this test is in a subdirectory of the bp tests

It's not, It's on it's own in `testing/examples/heatTransfer`

> why does this wrong include not fail all the time?

Is it possible the first pass isn't finding ZFP so those tests don't get turned on?

**Comment by pnorbert** [comment]
Oh, indeed, none of the HeatTransfer tests are turned on. I have only 670 tests on. I will need to check if this fix will bring back all of them.

**Comment by chuckatkins** [comment]
@williamfgc any idea what could be causing this failure: https://open.cdash.org/testDetails.php?test=804845916&build=6113280

**Comment by williamfgc** [comment]
@chuckatkins it's catching a `bad_alloc` when trying to parse a string in the C bindings. Not sure if related, but t way names are allocated were changed by @germasch and @eisenhauer is the maintainer, see #1230

**Comment by germasch** [comment]
> 236: C:\projects\adios2\testing\adios2\bindings\C\TestBPWriteTypes.cpp(192): error: Expected equality of these values:
> 236:   steps
> 236:     Which is: 0
> 236:   1
> 236: ERROR: found null pointer in call to adios2_attribute_is_value
> 236: 
> 236: adios2_attribute_is_value
> 236: C:\projects\adios2\testing\adios2\bindings\C\TestBPWriteTypes.cpp(205): error: Expected equality of these values:
> 236:   result
> 236:     Which is: 32762
> 236:   adios2_true
> 236:     Which is: 1
> 236: ERROR: found null pointer for attribute, in call to adios2_attribute_name
> 236: 
> 236: adios2_attribute_name
> 236: unknown file: error: C++ exception with description "bad allocation" thrown in the test body.

So it looks like the problem starts where it expects to find 1 step in the file, but there are actually 0. I'd believe the the following errors are related to that, e.g., the attribute doesn't exist, either. I'd wage a guess that this has nothing to do with the handling of strings in the C API (which doesn't allocate memory in the first place).

Instead, looking at the appveyor output, it looks to me like it's running tests in parallel, since the output of the various tests isn't sequential. If that's the case, considering that various tests in that file all write into the same `ctypes.bp` file, I'd expect it's a race with one test trying to read back that file when another tests has overwritten it.

**Comment by chuckatkins** [comment]
Just pushed the fix for unique file names.  It's unrelated to this and should be on it's own branch but they're both small changes and I really didn't feel like waiting on the cycle time for a separate pr.

**Comment by williamfgc** [comment]
@chuckatkins @germasch thanks for looking into this and getting a fix.

**Pull request merged**
