### PR TITLE
bp4dbg: executable

### PR DESCRIPTION
**Pull request by ax3l**
Mark the installed Python scripts related to `bp4dbg` as executable.

This mitigates an audit error in [homebrew/linuxbrew](https://github.com/ax3l/homebrew-core/commits/add-adios2) of the form:
```
adios2:
  * Non-executables were installed to "/home/axel/src/brew/opt/adios2/bin"
    The offending files are:
      /home/axel/src/brew/opt/adios2/bin/bp4dbg
Error: 1 problem in 1 formula detected
```

But generally it does not look clean to install a directory `bp4dbg/` inside `bin/`. Is there a way to clean this up or disable this?

```
$ ls -hal /home/axel/src/brew/opt/adios2/bin/
total 976K
drwxr-xr-x 3 axel axel 4.0K Oct 30 10:35 .
drwxr-xr-x 6 axel axel 4.0K Oct 30 10:35 ..
-r-xr-xr-x 1 axel axel 2.5K Oct 30 10:35 adios2-config
-r-xr-xr-x 1 axel axel  421 Sep 30 18:04 adios_deactivate_bp.sh
-r-xr-xr-x 1 axel axel  91K Oct 30 10:35 adios_reorganize
drwxr-xr-x 2 axel axel 4.0K Oct 30 10:35 bp4dbg
-r-xr-xr-x 1 axel axel 842K Oct 30 10:35 bpls
-r-xr-xr-x 1 axel axel  18K Oct 30 10:35 sst_conn_tool

$ ls -hal /home/axel/src/brew/opt/adios2/bin/bp4dbg/
total 72K
drwxr-xr-x 2 axel axel 4.0K Oct 30 10:35 .
drwxr-xr-x 3 axel axel 4.0K Oct 30 10:35 ..
-r--r--r-- 1 axel axel  25K Sep 30 18:04 bp4dbg_data.py
-r--r--r-- 1 axel axel 2.2K Sep 30 18:04 bp4dbg_idxtable.py
-r--r--r-- 1 axel axel  24K Sep 30 18:04 bp4dbg_metadata.py
-r-xr-xr-x 1 axel axel 3.3K Sep 30 18:04 bp4dbg.py
-r--r--r-- 1 axel axel 3.7K Sep 30 18:04 bp4dbg_utils.py
```

Removing them for now in https://github.com/Homebrew/homebrew-core/pull/45997

### CODE REVIEW

**Comment by chuckatkins** [comment]
Rather than just hammer these as executable, I think it makes more sense to restructure it appropriately.  They shouldn't really be executable and they should be structured into a proper module.  Something after install along the lines of:
```
rwxr-xr-x  bin/bp4dbg
rw-r--r--  <arch-independent-site-packages>/bp4dbg/__init__.py
rw-r--r--  <arch-independent-site-packages>/bp4dbg/data.py
rw-r--r--  <arch-independent-site-packages>/bp4dbg/idxtable.py
rw-r--r--  <arch-independent-site-packages>/bp4dbg/metadata.py
rw-r--r--  <arch-independent-site-packages>/bp4dbg/utils.py
```

**Comment by chuckatkins** [comment]
@pnorbert?

**Comment by pnorbert** [comment]
Fine with me if anyone changes this. I have no experience how to properly install a bunch of python scripts.

**Comment by hjafari-could** [comment]
Ok

**Comment by ax3l** [comment]
I agree with @chuckatkins's proposal as well, please feel free to adjust the PR as needed.

**Pull request merged**
