### PR TITLE
Update pybind11 to 2.13.1 

### PR DESCRIPTION
**Pull request by vicentebolea**
Superseedes #4226 

The enigmatic error with python in newer mac is that those mac are using newer numpy, newer numpy needs newer pybind11.

It also adds the two new mac builds here.

### CODE REVIEW

**Review by eisenhauer — DISMISSED** [review]

**Comment by vicentebolea** [comment]
@eisenhauer yay, it worked :)

**Comment by eisenhauer** [comment]
> @eisenhauer yay, it worked :)

Nice!

**Review by eisenhauer — APPROVED** [review]

**Comment by pnorbert** [comment]
This backport will fix issue #4287

**Comment by vicentebolea** [comment]
@pnorbert thanks for finding it

**Pull request merged**
