### PR TITLE
fixed a few type warnings for printf in manyvar

### PR DESCRIPTION
**Pull request by JasonRuonanWang**

### CODE REVIEW

**Comment by chuckatkins** [comment]
Either way this is good to go after the formatting fixes.  If you want to fix the remaining warnings that'd be great, but it's fine if not.

**Comment by JasonRuonanWang** [comment]
@chuckatkins Yes. I would definitely do it. But these are the only warnings I have seen. What else warnings did you see and how can I reproduce them?

**Comment by chuckatkins** [comment]
Check the dashboard with the [cdash] link in the status

**Comment by JasonRuonanWang** [comment]
I got this error which does not seem like a formatting thing.

Error: COMMIT_RANGE is empty or undefined

**Comment by chuckatkins** [comment]
Awesome!

**Pull request merged**
