### PR TITLE
bpls: fix some warnings for size_t printf arguments

### PR DESCRIPTION
**Pull request by germasch**
I'm just redoing #1554, since the CI kept on hanging on that one.

### CODE REVIEW

**Comment by germasch** [comment]
I'm not sure what's going on with the CI, though it seems it's working for others, but I've been having the same problem of the checks hanging despite multiple force pushes and moving this into a new PR. I can see on Circle CI that it passed, and  I see a green checkmark next to the commit, but github's status doesn't seem to get it.

At least this is only fixing some warnings (well, bugs with a 32-bit `size_t`, but who has those these days?).

**Comment by germasch** [comment]
Tried adding `[skip ci]` as @chuckatkins was mentioning elsewhere (not that it's really appropriate here), but seems no luck with that either. As I said before, this actually does pass CircleCI (https://circleci.com/gh/germasch/ADIOS2/tree/pr%2Fbpls_warnings), but it won't register correctly with github :(

**Comment by chuckatkins** [comment]
After we get through the release I'm going to look at some other CI options that can get us some better throughput.  The backlog that builds up from the 4 parallel builds that circle limits us to is really becoming a problem.

**Comment by germasch** [comment]
Thanks @chuckatkins . The problem I'm having isn't throughput/the queue limit, though, it is that even after all the jobs go through circleci and pass, they still don't report back to github. You should be able to see that they passed here in ~30 minutes: https://circleci.com/gh/germasch/ADIOS2/tree/pr%2Fbpls_warnings.  

This problem seems specific to me, though, so hopefully it'll just resolve itself eventually...

**Pull request merged**
