### PR TITLE
added check H5_USE_1xx_API to make sure H5 is not using older API.

### PR DESCRIPTION
**Pull request by guj**

### CODE REVIEW

**Review by chuckatkins — CHANGES_REQUESTED** [review]
Can you rebase this on release_28 re-target it for that branch so it can easily go into a patch release?

**Comment by chuckatkins** [comment]
Fixes #3149

**Comment by chuckatkins** [comment]
@eschnett does this fix #3149 for you?

**Comment by eschnett** [comment]
HDF5 offers a simpler way to achieve this. I recommend calling `H5Oget_info1` instead, which always accepts 2 arguments. Alternatively, `H5Oget_info2` always accepts 3 arguments. These functions should exist starting from HDF5 1.10.5.
```C++
#if H5_VERSION_GE(1, 10, 5)
    herr_t ret = H5Oget_info1(m_FileId, &oinfo);
#else
    herr_t ret = H5Oget_info(m_FileId, &oinfo);
#endif
```

**Comment by guj** [comment]
> HDF5 offers a simpler way to achieve this. I recommend calling `H5Oget_info1` instead, which always accepts 2 arguments. Alternatively, `H5Oget_info2` always accepts 3 arguments. These functions should exist starting from HDF5 1.10.5.
> 
> ```c++
> #if H5_VERSION_GE(1, 10, 5)
>     herr_t ret = H5Oget_info1(m_FileId, &oinfo);
> #else
>     herr_t ret = H5Oget_info(m_FileId, &oinfo);
> #endif
> ```

Yes, I am aware of that.  I just happen to prefer using the name get_info instead of get_info<N>.

**Comment by eschnett** [comment]
The condition `defined H5_USE_16_API && defined H5_USE_18_API` looks wrong. I think the individual API selection switches are exclusive.

Do you have CI infrastructure set up to test with both older and newer HDF5 versions?

**Comment by guj** [comment]
> The condition `defined H5_USE_16_API && defined H5_USE_18_API` looks wrong. I think the individual API selection switches are exclusive.
> 
> Do you have CI infrastructure set up to test with both older and newer HDF5 versions?

You are right.   It should be ||.  

Updated and checked with 1.13 with DEFAULT_API_VERSION=v18

**Comment by chuckatkins** [comment]
Rebased

**Pull request merged**
