### PR TITLE
EVpath upstream

### PR DESCRIPTION
**Pull request by eisenhauer**

### CODE REVIEW

**Comment by eisenhauer** [comment]
This EVpath update adds another mechanism for determining a fully-qualified hostname, necessary on Defiant.

**Comment by vicentebolea** [comment]
this is odd, I can only see one file changed in the diff

**Comment by eisenhauer** [comment]
Huh, that's not right...  Let me check to see what the update script did.

**Comment by eisenhauer** [comment]
Should be better now...

**Review by vicentebolea — APPROVED** [review]

**Comment by eisenhauer** [comment]
@vicentebolea Can you take a look here?  Unrelated test "Api.Python.BPWriteTypesHighLevelAPI.MPI" seems to be failing on windows....  (And oddly, CDash doesn't seem to be fully updated with the build results.)

**Comment by vicentebolea** [comment]
@eisenhauer resolved at #4268

**Pull request merged**
