### PR TITLE
Added performance monitor in DataMan

### PR DESCRIPTION
**Pull request by JasonRuonanWang**
A lot of near-real-time decision making features that we proposed in the HBPS project will need this.

### CODE REVIEW

**Comment by JasonRuonanWang** [comment]
Does anyone understand what this error is?

**Comment by pnorbert** [comment]
I don't understand it. What happened to the windows compilers? Reorganize.h has not changed for a while.

**Comment by JasonRuonanWang** [comment]
It's probably because some settings were changed so that some warnings that previously existed are now deemed as errors.

**Comment by pnorbert** [comment]
No, warnings on windows were always treated as errors. However I don't know when we moved to vs 2019

**Comment by chuckatkins** [comment]
> No, warnings on windows were always treated as errors

They weren't until recently.  In the MPI work @bradking did he cleaned up the few straggling warnings and was able to finally turn on warnings as errors for msvc.

> Hwever I don't know when we moved to vs 2019
We've been building with 2017 and 2019 for a few months now

**Comment by bradking** [comment]
I encountered the same warning (treated as error) over in #2318, and added a commit there to address it.

**Comment by chuckatkins** [comment]
> > However I don't know when we moved to vs 2019
> 
> We've been building with 2017 and 2019 for a few months now

@pnorbert it's also possible that Azure has updated the 2019 compiler image to a newer patch release which may in turn be producing different warnings.

**Comment by chuckatkins** [comment]
> > > However I don't know when we moved to vs 2019
> > 
> > 
> > We've been building with 2017 and 2019 for a few months now
> 
> @pnorbert it's also possible that Azure has updated the 2019 compiler image to a newer patch release which may in turn be producing different warnings.

Digging in a bit it seems that's exactly what happened.  If you look at a build from the last merge of the release you can see in the configure output:
```
-- The C compiler identification is MSVC 19.25.28614.0
```
While in this one you get:
```
-- The C compiler identification is MSVC 19.26.28805.0
```

**Comment by JasonRuonanWang** [comment]
Any suggestions what I should do?

**Comment by bradking** [comment]
I've opened #2322 specifically to fix the new MSVC warning with no other changes.  Once that is merged this can be rebased.

**Comment by JasonRuonanWang** [comment]
> I've opened #2322 specifically to fix the new MSVC warning with no other changes. Once that is merged this can be rebased.

Thanks!

**Comment by chuckatkins** [comment]
@JasonRuonanWang you should be able to rebase the ci failures away now.

**Pull request merged**
