### PR TITLE
Port CMake python tooling to use upstream FindPython

### LINKED ISSUE #1951: python3 not detected, current master with python support is broken
I am trying to build Adios2 with python3 but cmake detects as python2:
```
cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Blosc (missing: BLOSC_LIBRARY BLOSC_INCLUDE_DIR) (Required is at least version "1.7")
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1") found components:  C CXX 
-- Could NOT find DataSpaces (missing: DATASPACES_VERSION DATASPACES_INCLUDE_DIR DATASPACES_LIBRARIES DSPACES_LIBRARY) (Required is at least version "1.8")
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.17") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.17", minimum required is "2.7.17") 
-- Found PythonModule_numpy: /usr/local/lib/python2.7/dist-packages/numpy  
-- Could NOT find PythonModule_mpi4py (missing: PythonModule_mpi4py_PATH) 
CMake Error at /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonFull (missing: mpi4py)
Call Stack (most recent call first):
  /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPythonFull.cmake:54 (find_package_handle_standard_args)
  cmake/DetectOptions.cmake:199 (find_package)
  CMakeLists.txt:133 (include)
```

I am sure that I provided python3:
```
/usr/local/bin/python --version
Python 3.6.9
```

I also installed numpy and mpi4py for python3:
```
/usr/local/bin/python -c "import numpy"
/usr/local/bin/python -c "import mpi4py"
```

There is no mpi4py installed for python2 (this is why I got an error message in the above, which make sense)

I will appreciate any help and advice.

Thanks.

### PR DESCRIPTION
**Pull request by chuckatkins**
Fixes #1951

### CODE REVIEW

**Comment by chuckatkins** [comment]
@jychoi-hpc @AaronV77 @williamfgc I believe this should work now to address the issue in #1951.  Could one of you please give it a test to see if it works for you?

**Comment by AaronV77** [comment]
@chuckatkins I'll give it a shot.

**Comment by AaronV77** [comment]
Alright so after updating OpenSSL and CMake, it still gave me problems finding python and still had it turned off. 

Screen Shot 2020-02-27 at 5 37 08 PM

Here is a picture of it turned off:

Screen Shot 2020-02-27 at 5 42 06 PM

What is nice to see, is that the PNG is actually turned on. This was in the same boat for me as Python but I eventually got it to work.

**Comment by pnorbert** [comment]
It fixes my case where Python 3 and Python 2 are both present on the system.
```
-- Found Python: /usr/bin/python3.6 (found version "3.6.9") found components: Interpreter Development NumPy 
-- Found Python: /usr/bin/python3.6 (found version "3.6.9") found components: Interpreter 
-- Found PythonModule_mpi4py: /usr/local/lib/python3.6/dist-packages/mpi4py  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
```

**Comment by chuckatkins** [comment]
@AaronV77 

> install CMake from the source because Centos 8 doesn't have an RPM package that is newer than 3.11.

The easiest thing to do is just use the prebuilt tar.gz binaries.  They should run out of the box on most all a86_64 Linux environments.

> This was in the same boat for me as Python but I eventually got it to work.
> This was on Centos 8.

So, I've tested on CentOS 8 and I can't reproduce the issue you're having.  After installing the python36, python36-devel, and python3-numpy packages, I get this for a serial build:
```
$ /opt/cmake/3.16.4/bin/cmake ../source
...
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND MPI_Fortran_FOUND C Fortran)
...
-- Found Python: /usr/bin/python3.6 (found version "3.6.8") found components: Interpreter Development NumPy 
...
ADIOS2 build configuration:
  ADIOS Version: 2.5.0.506
...
  Features:
...
    Build Options:
...
      MPI       : OFF
...
      Python    : ON
...
-- Configuring done
```
```
$ grep '^_Python' CMakeCache.txt 
_Python_EXECUTABLE:FILEPATH=/usr/bin/python3.6
_Python_INCLUDE_DIR:PATH=/usr/include/python3.6m
_Python_LIBRARY_RELEASE:FILEPATH=/usr/lib64/libpython3.6m.so
_Python_NumPy_INCLUDE_DIR:PATH=/usr/lib64/python3.6/site-packages/numpy/core/include
...
```
And then similarly with MPI (note that Python is still found but not mpi4py so support is disabled for adios):
```
$ /opt/cmake/3.16.4/bin/cmake ../source/
...
-- Found MPI: TRUE (found version "3.1") found components: C Fortran CXX 
...
-- Found Python: /usr/bin/python3.6 (found version "3.6.8") found components: Interpreter Development NumPy 
-- Could NOT find PythonModule_mpi4py (missing: PythonModule_mpi4py_PATH) 
...
ADIOS2 build configuration:
  ADIOS Version: 2.5.0.506
 ...
  Features:
...
    Build Options:
...
      MPI       : ON
...
      Python    : OFF
...
-- Configuring done
```
```
$ grep '^_Python' CMakeCache.txt 
_Python_EXECUTABLE:FILEPATH=/usr/bin/python3.6
_Python_INCLUDE_DIR:PATH=/usr/include/python3.6m
_Python_LIBRARY_RELEASE:FILEPATH=/usr/lib64/libpython3.6m.so
_Python_NumPy_INCLUDE_DIR:PATH=/usr/lib64/python3.6/site-packages/numpy/core/include
```

**Comment by AaronV77** [comment]
@chuckatkins Okay so I don't install python through an RPM package and use Minicaonda aka. Anaconda. So here is my output of the same command you did:

```
$ grep '^_Python' CMakeCache.txt 
(base) [valorosoa@localhost build]$ grep '^_Python' CMakeCache.txt 
_Python_CONFIG:FILEPATH=_Python_CONFIG-NOTFOUND
_Python_EXECUTABLE:FILEPATH=/home/valorosoa/miniconda3/bin/python3.7
_Python_LIBRARY_RELEASE:FILEPATH=_Python_LIBRARY_RELEASE-NOTFOUND
_Python_CONFIG-ADVANCED:INTERNAL=1
_Python_EXECUTABLE-ADVANCED:INTERNAL=1
_Python_INTERPRETER_PROPERTIES-ADVANCED:INTERNAL=1
_Python_INTERPRETER_PROPERTIES:INTERNAL=Python;3;7;4;64;m;cpython-37m-x86_64-linux-gnu;/home/valorosoa/miniconda3/lib/python3.7;/home/valorosoa/miniconda3/lib/python3.7;/home/valorosoa/miniconda3/lib/python3.7/site-packages;/home/valorosoa/miniconda3/lib/python3.7/site-packages
_Python_INTERPRETER_SIGNATURE-ADVANCED:INTERNAL=1
_Python_INTERPRETER_SIGNATURE:INTERNAL=ef8dafd0c5ed4ce9de48a8427a99343c
_Python_LIBRARY_RELEASE-ADVANCED:INTERNAL=1
(base) [valorosoa@localhost build]$ 
```

**Comment by chuckatkins** [comment]
@AaronV77 I'm still not able to reproduce this with a few different configurations of miniconda.  I'm going to go ahead and merge this since it addresses finding python for several different configurations, even if not yours.  If you're problem still persists, please make a new issue with details on how to reproduce your environment and we can iterate on that specifically.

**Comment by AaronV77** [comment]
@chuckatkins Alright I will try to get around to it today at some point.

**Pull request merged**
