### PR TITLE
Rename internal data type enumeration from Type to DataType

### PR DESCRIPTION
**Pull request by bradking**
The enumeration added by #2310 is named `Type`, but `DataType` more precisely describes its purpose.

### CODE REVIEW

**Comment by bradking** [comment]
CI is happy here except for timeouts on `macos macos1015_xcode111_make` which occurred repeatedly.

**Comment by bradking** [comment]
I've opened #2322 specifically to fix the new MSVC warning with no other changes.  Once that is merged this can be rebased.

**Comment by ax3l** [comment]
I saw that merging this PR two days ago broke our nightly integration compiling against ADIOS2 master. We use `adios2::GetType<...>` which we thought is public API and is now renamed, what do you recommend? :)

Ref.: https://dev.azure.com/axelhuebl/openPMD-api/_build/results?buildId=392&view=results

cc @franzpoeschel

**Comment by bradking** [comment]
@ax3l thanks.  I had not intended to change the public-facing name.  I've reverted that part in #2342.

**Comment by pnorbert** [comment]
Thanks. It broke E3SM's adios driver too. There are functions there to map between pnetcdf and adios2 types. 

However, in the future it may be useful for exposing the DataType publicly as well. It would make coding cleaner in my opinion.

**Pull request merged**
