### PR TITLE
ci: Set openmpi and openmp parameters to make an efficient use of the CI

### PR DESCRIPTION
**Pull request by vicentebolea**
fixes: #3897

### CODE REVIEW

**Comment by anagainaru** [comment]
Is this going to make the testing (and thus the CI) slower? Do we really want to keep the BP3 testing? Could we maybe separate it to only test BP3 in the nightly builds?

**Comment by eisenhauer** [comment]
I'm curious if this really fixes it and why.  This isn't big data.  If one of the compressors is taking more than 2 minutes to do something with it, that seems like a non-viable compressor.

**Comment by vicentebolea** [comment]
I found that this problem occurs on my laptop when connected to a ethernet network but not when connected to the wifi network. I could figure out that this is due to openmpi picking certain network interfaces, a easy workaround is to use the lo interface

**Comment by eisenhauer** [comment]
> I found that this problem occurs on my laptop when connected to a ethernet network but not when connected to the wifi network. I could figure out that this is due to openmpi picking certain network interfaces, a easy workaround is to use the lo interface

Well, maybe...  But why only this test?  MGard doesn't use MPI, but it does use OpenMP.  I build MGard manually on my OSX laptop and these tests have no problems.  I'm wondering if on whatever platform this is running OpenMP isn't playing well with MPI, resulting in the issues that you're seeing.  (I could use the docker image and dig further, but I'm off at a conference, so little spare time for the moment.)

**Comment by vicentebolea** [comment]
> Well, maybe... But why only this test? MGard doesn't use MPI, but it does use OpenMP. I build MGard manually on my OSX laptop and these tests have no problems. I'm wondering if on whatever platform this is running OpenMP isn't playing well with MPI, resulting in the issues that you're seeing. (I could use the docker image and dig further, but I'm off at a conference, so little spare time for the moment.)

hmm, so two things happened here:

- The real culcript was the that we were using n*4) number of mpi tasks and each of the task was using n*2 number of threads (n=2) this was just too much for the weak VPS that github gives us.
- The interface thing was affecting time to time different mpi test in random fashion

**Comment by vicentebolea** [comment]
@scottwittenburg if this makes sense to you please approve so that it gets merged and we get a green dashboard :sunglasses:

**Comment by vicentebolea** [comment]
Yay, it's all green again :)

**Review by eisenhauer — APPROVED** [review]
Looks good.

**Comment by scottwittenburg** [comment]
I've rebased on this change, and now my ci reproducer builds are happening in serial, which seems like an unintended consequence.

**Pull request merged**
