### PR TITLE
heat transfer read/write worked with dataman

### PR DESCRIPTION
**Pull request by JasonRuonanWang**

### CODE REVIEW

**Comment by pnorbert** [comment]
1. examples/heatTransfer/heat_dataman.xml sets the reader transport to POSIX and that fails:
ERROR: wan transport POSIX not supported or not provided in IO AddTransport, in call to Open

2. If I change that to ZMQ, and run 2 writers and 2 readers in two terminals, they hang
$ mpirun -np 2 ./bin/heatTransfer_read /home/adios/work/ADIOS2/examples/heatTransfer/heat_dataman.xml heat.bp 2 1
mpirun -n 2 ./bin/heatTransfer_write_adios2 /home/adios/work/ADIOS2/examples/heatTransfer/heat_dataman.xml heat.bp 2 1 5 6 3 1

There is no obvious handshake between them, the writer runs to the very end and then hangs.

3. Same thing if I run them as MPMD run (I don't know if this is the supposed way to run them)
mpirun -n 2 ./bin/heatTransfer_write_adios2 /home/adios/work/ADIOS2/examples/heatTransfer/heat_dataman.xml heat.bp 2 1 5 6 100 100 : -n 2  ./bin/heatTransfer_read /home/adios/work/ADIOS2/examples/heatTransfer/heat_dataman.xml heat.bp 2 1

3. They seem to work in 1 writer and 1 reader setup, at least they finish. But the result data.0 is all corrupt data. 
$ mpirun -np 1 ./bin/heatTransfer_read /home/adios/work/ADIOS2/examples/heatTransfer/heat_dataman.xml heat.bp 1 1
$ mpirun -n 1 ./bin/heatTransfer_write_adios2 /home/adios/work/ADIOS2/examples/heatTransfer/heat_dataman.xml heat.bp 1 1 5 6 3 1

$ cat data.0 
rank=0 size=5x6 offsets=0:0 step=0
 time   row   columns 0...5
                0        1        2        3        4        5
--------------------------------------------------------------
    0    0        0        0        0        0        0        0
    0    1        0        0 3.6e-308 1.4e-309        0 2.1e-314
    0    2 2.1e-314 4.9e-324 4.9e-324        0        0 2.1e-314
    0    3        0        0        0        0        0 2.1e-311
    0    4 1.4e-308-3.2e-319 1.4e-309   4e-310 2.8e-309 1.4e-312

**Comment by pnorbert** [comment]
Please ignore the first error, I ran with the wrong xml file.

**Comment by JasonRuonanWang** [comment]
All problems have been fixed and now it works with N-to-N multi-rank cases. Please check and merge. @pnorbert

**Comment by pnorbert** [comment]
It does work N-to-N. However, there is still one problem: only 1 step, the first step is processed by the reader, then it quits. 

$ mpirun -n 4 ./bin/heatTransfer_write_adios2 /home/adios/work/worktree/ADIOS2/release/examples/heatTransfer/heat_dataman.xml heat.bp 2 2 5 6 3 1
[WANZmq] IP Address 127.0.0.1
[WANZmq] Port 12307
[WANZmq] Open Mode Write
[WANZmq] IP Address 127.0.0.1
[WANZmq] Port 12306
[WANZmq] Open Mode Write
[WANZmq] IP Address 127.0.0.1
[WANZmq] Port 12309
[WANZmq] Open Mode Write
[WANZmq] IP Address 127.0.0.1
[WANZmq] Port 12308
[WANZmq] Open Mode Write
Step 1:
Step 2:
Step 3:
Total runtime = 0.0670421s


$ mpirun -np 4 ./bin/heatTransfer_read /home/adios/work/worktree/ADIOS2/release/examples/heatTransfer/heat_dataman.xml heat.bp 2 2
[WANZmq] IP Address 127.0.0.1
[WANZmq] Port 12306
[WANZmq] IP Address 127.0.0.1
[WANZmq] Port 12307
[WANZmq] IP Address 127.0.0.1
[WANZmq] Port 12308
[WANZmq] IP Address 127.0.0.1
[WANZmq] Port 12309
[WANZmq] Open Mode Read
[WANZmq] Open Mode Read
[WANZmq] Open Mode Read
[WANZmq] Open Mode Read
rank 1 reads 2D slice 5 x 6 from offset (5,0)
gndx       = 10
gndy       = 12
rank 0 reads 2D slice 5 x 6 from offset (0,0)
rank 2 reads 2D slice 5 x 6 from offset (0,6)
Processing step 0
rank 3 reads 2D slice 5 x 6 from offset (5,6)

$ cat data.0 
rank=0 size=5x6 offsets=0:0 step=0
 time   row   columns 0...5
                0        1        2        3        4        5
--------------------------------------------------------------
    0    0        1        1      2.7        1    -0.73        1
    0    1     -1.9     -1.9     -0.2     -1.9     -3.7     -1.9
    0    2      1.4      1.4      3.2      1.4     -0.3      1.4
    0    3      1.4      1.4      3.2      1.4     -0.3      1.4
    0    4     -1.9     -1.9     -0.2     -1.9     -3.7     -1.9

It should be 

$ cat data.0 
rank=0 size=5x6 offsets=0:0 step=0
 time   row   columns 0...5
                0        1        2        3        4        5
--------------------------------------------------------------
    0    0        1        1      2.7        1    -0.73        1
    0    1     -1.9     -1.9     -0.2     -1.9     -3.7     -1.9
    0    2      1.4      1.4      3.2      1.4     -0.3      1.4
    0    3      1.4      1.4      3.2      1.4     -0.3      1.4
    0    4     -1.9     -1.9     -0.2     -1.9     -3.7     -1.9
rank=0 size=5x6 offsets=0:0 step=1
 time   row   columns 0...5
                0        1        2        3        4        5
--------------------------------------------------------------
    1    0      1.2      1.2      1.5     0.81     0.12     0.47
    1    1     0.31    -0.32     0.37    -0.67     -1.7       -1
    1    2      1.1      1.1      1.8     0.76    -0.28     0.41
    1    3      1.1      1.1      1.8     0.76    -0.28     0.41
    1    4     0.31    -0.32     0.37    -0.67     -1.7       -1
rank=0 size=5x6 offsets=0:0 step=2
 time   row   columns 0...5
                0        1        2        3        4        5
--------------------------------------------------------------
    2    0      1.7      1.3      1.4     0.95     0.54     0.68
    2    1      1.1     0.52     0.54   -0.088    -0.71     -0.5
    2    2      1.3     0.95      1.2     0.47    -0.22    0.055
    2    3      1.3     0.95      1.2     0.47    -0.22    0.055
    2    4     0.86     0.33     0.41    -0.29    -0.98     -0.7

**Pull request merged**
