### PR TITLE
Removing printf statement

### LINKED ISSUE #1389: "token:" message from libtaustubs.so
https://github.com/ornladios/ADIOS2/blob/806ed20de90f91e7d433f1c90937aa79f7d0f98a/source/adios2/toolkit/profiling/taustubs/tautimer.cpp#L111

XGC people are reporting that they got "token:" message from stdout and found that it's from ADIOS (as above). I am wondering if there is any way to build Adios without creating or using "libtaustubs.so". 

Or, is there any way to supress "token:" message?

### PR DESCRIPTION
**Pull request by khuck**
Removing non-essential printf statement to fix #1389

### CODE REVIEW

**Comment by khuck** [comment]
I also pushed a change to disable the TAU profiling entirely by default.  Without the ```#define TAU_USE_STUBS```, the profiler call macros will be removed by the compiler.

**Comment by khuck** [comment]
I also found a bug when building on Apple, and pushed a fix for that.

**Comment by khuck** [comment]
thanks @germasch that's a better solution.

**Comment by khuck** [comment]
Sorry, boogered up the commits.  Feel free to squash.

**Comment by eisenhauer** [comment]
Clang-format 7.0.1...

**Comment by khuck** [comment]
> Clang-format 7.0.1...

Ugh.  That'll teach me to fix other people's bugs.  Fixed.

**Comment by germasch** [comment]
FWIW, the CI failure I think is just a random race in the build (and I'm glad to see I'm not the only one hitting that). I think the usual way to deal with that is to amend you last commit (without changing anything, that'll just update the timestamp), then force-push and keep your fingers crossed.

**Comment by khuck** [comment]
I saw a "re-run failed tests" link, so I clicked that...

**Comment by germasch** [comment]
Just clicking sounds even better -- I don't think I have luxury of that level of access. Sometimes it's taken me like 5 amends / force pushes to get it to go through...

**Comment by eisenhauer** [comment]
Kevin, please rebase on current master.  (There have been issues with CircleCI.  Changes there messed things up so nothing was really passing.  Current master fixes them.)

**Comment by eisenhauer** [comment]
Kevin, I thought you might be indisposed, so I pulled these changes into another branch, rebased and merged.  Thanks!

**Comment by khuck** [comment]
@eisenhauer sorry, not out of commission yet, just confused about the status, I thought it was merged already.  Thanks for taking care of it!

**Pull request closed without merging**
