### PR TITLE
Zero Data Variable Test

### PR DESCRIPTION
**Pull request by eisenhauer**
Add a test that has a global variable which has zero elements contributed by some node.

### CODE REVIEW

**Comment by eisenhauer** [comment]
@JasonRuonanWang, this PR adds an SST test in which a single global variable has zero elements contributed by one rank (in this case, all are contributed by another).  The test passes with FFS-based marshaling and fails with BP marshaling.  This is likely what @pnorbert reported in issue #1111 .   I've marked the BP tests as WILL_FAIL in CMake.  Not sure if that will let this PR pass, or if we'll need to fix the bug before it can go in, but maybe this is the test case for committing tests that don't pass...

**Comment by chuckatkins** [comment]
@eisenhauer will this be targeting the release?  If so then please edit the base branch to be `release` and add the `2.4.0` milestone.

**Comment by eisenhauer** [comment]
I'm going to close this and resubmit it reworked after the release.

**Comment by ax3l** [comment]
Oh, so 2.4.0 will not be able to write zero-sized data yet?

**Comment by williamfgc** [comment]
@ax3l this is related to the SST engine which is using the same serializer/deserializer,  if you're talking about files I have a [test](https://github.com/ornladios/ADIOS2/blob/master/testing/adios2/engine/bp/TestBPWriteMultiblockRead.cpp) (without trying compression), look for the Zero keyword in that link. Please use that for your tests and report if there are issues. Thanks!

**Comment by eisenhauer** [comment]
@ax3l OK, zero contribution tests are back in PRs #1622 and  #1624 (simplified version).   They don't do compression, but at present they demonstrate a problem with SST and BP marshaling.  The nature of the problem seems to be that the BP.SST tests are unstable, succeeding or failing based upon a data race created by a bad read request.  Hopefully it can get sorted out soon.

**Pull request closed without merging**
