### PR TITLE
Adding NullEngine

### PR DESCRIPTION
**Pull request by williamfgc**
Addressing #1132 
Added C++11 bindings null engine

### CODE REVIEW

**Comment by chuckatkins** [comment]
Please rebase off current master as the version of clang-format was just bumped from 3.8.1 to 7.0.1

**Comment by germasch** [comment]
What's the goal of the "NULL" engine? From #1132, it sounds like it's like `/dev/null` for writing. It looks to me like `SkeletonWriter` basically fits the bill. For reading, I don't think it's clear what one would want.

Independently of that, it might be useful to have a Transport that just sinks everything into a black hole == if one wanted to benchmark, e.g., bp3 serialization without the cost of the actual I/O.

**Comment by williamfgc** [comment]
@germasch yes, that's the goal, switching to NULL should allow to measure adios2 engine overhead in an application. @pnorbert and @jychoi-hpc have used this approach for a long time in adios1.x

**Comment by williamfgc** [comment]
After a discussion with @chuckatkins I am merging this for initial test. If the intention is to only "nullify" the core, we can look for an alternative. This is currently working on the write and read sides to address #1132.

**Pull request merged**
