### PR TITLE
#725 enable test with mpi oversubscribe

### PR DESCRIPTION
**Pull request by williamfgc**
OMPI_MCA_rmaps_base_oversubscribe=yes must be either passed to cmake or be already an
env variable when running cmake and ctest

### CODE REVIEW

**Comment by chuckatkins** [comment]
The entire logic block here can be reworked to be much simpler I think.  The use case is to oversubscribe when < 4 processors are detected and the OpenMPI env var explicitly says it's okay, right?  FindMPI already sets MPIEXEC_MAX_NUMPROCS to the detected number of physical cores.  Given that, the whole logic block can be reduced to:
```cmake
if(ADIOS2_HAVE_MPI)
  if(MPIEXEC_MAX_NUMPROCS LESS 4 AND "$ENV{OMPI_MCA_rmaps_base_oversubscribe}")
    message(STATUS "OpenMPI oversubscribe detected: raising MPIEXEC_MAC_NUMPROCS to 4 for testing")
    set(MPIEXEC_MAX_NUM_PROCS 4 CACHE STRING "" FORCE)
  endif()
  ...
endif()
```
I think that's right.  Would that work?

**Comment by williamfgc** [comment]
@chuckatkins cmake had issues with MPIEXEC_MAX_NUMPROCS  https://gitlab.kitware.com/cmake/cmake/merge_requests/1405 which were replicated on  my Mac using different cmake versions. That's why I have to use something more backwards compatible like `cmake_host_system_information`

**Comment by chuckatkins** [comment]
We include a private copy of the upstream FindMPI module that should already be patched for this: https://github.com/ornladios/ADIOS2/blob/cefab223f7bad996449c081d7b9805e7ca13bc01/cmake/upstream/FindMPI.cmake#L1291-L1292
so the `cmake_host_system_information` workaround in the main `CMakeLists.txt` shouldn't be necessary anymore.  Does it still not work correctly for you?

**Comment by williamfgc** [comment]
@chuckatkins yes, that works using cmake 3.12 on my Mac (we were forced to upgrade).

**Pull request merged**
