### PR TITLE
[WIP] Changing shape fix

### PR DESCRIPTION
**Pull request by pnorbert**

### CODE REVIEW

**Comment by williamfgc** [comment]
addresses #1071

**Comment by chuckatkins** [comment]
Just rebased on current master

**Comment by chuckatkins** [comment]
@pnorbert can you please close this as a branch on the main repo and resubmit it as a branch from your repo?

**Comment by pnorbert** [comment]
It was supposed to be a short living fix branch, and it's not mine. I
thought it was already merged as a fix. @wfgodoy should take ownership of
it.

**Comment by williamfgc** [comment]
@chuckatkins @pnorbert let me migrate it, it's not passing all tests so it's WIP

**Comment by williamfgc** [comment]
Closing this PR to remove branch from upstream. I will work on this from my branch.

**Pull request closed without merging**
