### PR TITLE
Added IO.GetVariableNames() function which returns a vector of name-t…

### LINKED ISSUE #2196: Faster version of available_variables() in python bindings.
As @khuck & co reported, available_variables() is a costly call. 
Need a faster way to get the list of variables in python.

A followup PR is introducing 'get_variable_names()' that returns a list of pairs (name, type). The low-level python and the original C++ API call is IO.GetVariableNames() that returns a vector of pairs.

### PR DESCRIPTION
**Pull request by pnorbert**
…ype string pairs. It is much faster than the current AvailableVariables() function. Added a python high-level function 'get_variable_names()' which returns a list of string-pairs (name,type). Added python test. Fixes #2196

### CODE REVIEW

**Comment by williamfgc** [comment]
@pnorbert thanks, I think this is great! Also, I'm thinking the current `available_variables` could be further generalized by passing a list of keys to only extract certain info. Something like: `vars_info = fstep.available_variables(keys=[type, dims, ...])` while an empty list would the default returning everything that way current behavior and API are not broken. But if this what 90% of people would do, it's fine to have a separate function.

**Comment by pnorbert** [comment]
This new function is ready to merge but it does not serve too much purpose for the TAU use case after figuring out that the problem was the use of a debug build. Also @williamfgc's comment is valid, maybe we should rework the high-level python function instead of having yet another function. The C++/low-level python extra function GetVariableNames though is fine I think.

**Comment by williamfgc** [comment]
@pnorbert let me work on overloading `available_variables` . When are you freezing for `v2.6.0`?

**Comment by pnorbert** [comment]
Thanks, I appreciate your help. Feature freeze is by May 15, planned release is end of May.

**Comment by chuckatkins** [comment]
So, do we merge this, close it in favor of a different approach, or leave it as is and mark it WIP?

**Comment by pnorbert** [comment]
Superseeded by #2214

**Pull request closed without merging**
