### PR TITLE
added support to query BP5 files

### PR DESCRIPTION
**Pull request by guj**
added function to use MinBlocksInfo to browse bp5 statistics.

### CODE REVIEW

**Comment by eisenhauer** [comment]
Changes look good.  Is any of the query stuff tested in CI?
(The readthedocs failure is spurious, probably just need to force push again to rerun.)

**Comment by guj** [comment]
> Changes look good. Is any of the query stuff tested in CI?
There was some query tests, but for bp4. Will add bp5 related ones.  

> (The readthedocs failure is spurious, probably just need to force push again to rerun.)

Strange.  @vicentebolea do you have any idea why read the doc failed?

**Review by anagainaru — COMMENTED** [review]
Looks good to me. I am trying to test this with BP5/BP4. What bp file should I use?

**Comment by vicentebolea** [comment]
> Strange. @vicentebolea do you have any idea why read the doc failed?

I thank that as @eisenhauer said the build failure was spurious since it passed after retrying

**Comment by guj** [comment]
> Looks good to me. I am trying to test this with BP5/BP4. What bp file should I use?

Should work with any.  
I will upload my python test script later today.

**Comment by anagainaru** [comment]
Issue #3707 is still not fixed by this PR. I still get:
```
C++ exception with description "[Fri Sep 15 14:28:40 2023] [ADIOS2 EXCEPTION] <Engine> <BP5Reader> <BeginStep> : BeginStep called in random access mode" thrown in the test body.
```

**Comment by guj** [comment]
> Issue #3707 is still not fixed by this PR. I still get:
> 
> ```
> C++ exception with description "[Fri Sep 15 14:28:40 2023] [ADIOS2 EXCEPTION] <Engine> <BP5Reader> <BeginStep> : BeginStep called in random access mode" thrown in the test body.
> ```

Because BP5 only loads metadata after begin step. 
I am changing that test

**Review by anagainaru — APPROVED** [review]

**Comment by guj** [comment]
@anagainaru 
I just added a few more cleanups. would you approve again? thanks

**Comment by anagainaru** [comment]
@guj when you rebase I will have to approve again :) 
If you let me know when you are done with everything and it's ready to merge I can approve then and you can squash merge the PR

**Review by anagainaru — APPROVED** [review]

**Pull request merged**
