### PR TITLE
Fix install tests

### LINKED ISSUE #1842: Install tests don't work with multi-config generators or on mac
Install tests seem to only work on Linux right now.  

See https://open.cdash.org/testDetails.php?test=816980151&build=6179972 and https://open.cdash.org/testDetails.php?test=813895347&build=6179968

### PR DESCRIPTION
**Pull request by chuckatkins**
Address various issues with the install tests.

Combines #1845 and #1852
Fixes #1842

### CODE REVIEW

**Comment by KyleFromKitware** [comment]
@chuckatkins Please hold off on merging this for now. I'm working on getting a fix into CMake that will allow me to do an improved version of the install name directory stuff.

**Comment by chuckatkins** [comment]
> I'm working on getting a fix into CMake that will allow me to do an improved version of the install name directory stuff.

ADIOS still needs to stay compatible with 3.6 for the moment so even if it's in upstream CMake we can't necessarily rely on it.

**Comment by KyleFromKitware** [comment]
> ADIOS still needs to stay compatible with 3.6 for the moment so even if it's in upstream CMake we can't necessarily rely on it.

No, but we can use it if it's available and fall back to the current fix if it's not.

**Comment by KyleFromKitware** [comment]
@chuckatkins I just pushed the commit that fixes multi-config builds on Windows. I initially pushed it to your Azure branch, but it looks like it got lost during one of your force-pushes. I recovered it from my local build :)

**Comment by KyleFromKitware** [comment]
This is blocked by [cmake/cmake!3989](https://gitlab.kitware.com/cmake/cmake/merge_requests/3989). Please hold off on merging until that is merged.

**Comment by KyleFromKitware** [comment]
[cmake/cmake!3989](https://gitlab.kitware.com/cmake/cmake/merge_requests/3989) has now been merged. This PR is unblocked.

**Pull request merged**
